import{useState}from'react';
import{creativesApi}from'../api/creatives';
import{label}from'../lib/presentation';
import type{CreativeScene}from'../types';

const sceneTypes=['AVATAR','PRODUCT','TEXT','COMPARISON','PROS_CONS','PRICE','WARNING','CTA','BROLL','MIXED'];
const speakers:[string,string][]=[['NONE','Nenhum'],['BRUNO','Bruno'],['CAROL','Carol'],['NARRATOR','Narrador']];
const purposes=['HOOK','BENEFIT','LIMITATION','CONCLUSION','CTA','CONTEXT','EVIDENCE','DISCLOSURE'];
const avatarStates:Record<string,[string,string][]>= {BRUNO:[['NEUTRAL','Neutro'],['EXPLAINING','Explicando'],['APPROVING','Aprovando'],['WARNING','Alerta'],['QUESTIONING','Questionando'],['POINTING','Apontando'],['COMPARING','Comparando']],CAROL:[['NEUTRAL','Neutro'],['CURIOUS','Curiosa'],['APPROVING','Aprovando'],['WARNING','Alerta'],['QUESTIONING','Questionando'],['AGREEING','Concordando'],['THINKING','Pensando']]};
const usesAvatar=(speaker:string)=>speaker==='BRUNO'||speaker==='CAROL';
const draftFrom=(scene:CreativeScene)=>({sceneType:scene.sceneType,speaker:scene.speaker,purpose:scene.purpose,narrationText:scene.narrationText??'',onScreenText:scene.onScreenText??'',visualInstruction:scene.visualInstruction??'',avatarState:usesAvatar(scene.speaker)?scene.avatarState??'NEUTRAL':'',durationSeconds:String(scene.durationSeconds??'')});

export function CreativeSceneEditor({creativeId,scene,index,count,editable,onRefresh}:{creativeId:string;scene:CreativeScene;index:number;count:number;editable:boolean;onRefresh:()=>void}){
  const[editing,setEditing]=useState(false);const[draft,setDraft]=useState(()=>draftFrom(scene));const[error,setError]=useState('');const[saving,setSaving]=useState(false);
  const set=(key:keyof typeof draft,value:string)=>setDraft(current=>({...current,[key]:value}));
  const setSpeaker=(speaker:string)=>setDraft(current=>({...current,speaker,avatarState:usesAvatar(speaker)?(avatarStates[speaker].some(([value])=>value===current.avatarState)?current.avatarState:'NEUTRAL'):''}));
  const cancel=()=>{setDraft(draftFrom(scene));setError('');setEditing(false)};
  const save=async()=>{setSaving(true);setError('');try{await creativesApi.patchScene(creativeId,scene.id,{sceneType:draft.sceneType,speaker:draft.speaker,purpose:draft.purpose,narrationText:draft.narrationText||null,onScreenText:draft.onScreenText||null,visualInstruction:draft.visualInstruction||null,avatarState:draft.avatarState||null,durationSeconds:draft.durationSeconds?Number(draft.durationSeconds):null});onRefresh();setEditing(false)}catch(e){setError(e instanceof Error?e.message:'Não foi possível salvar a cena.')}finally{setSaving(false)}};
  if(editing)return <div className="creative-scene-edit"><label className="scene-edit-type">Tipo da cena<select aria-label="Tipo da cena" value={draft.sceneType} onChange={e=>set('sceneType',e.target.value)}>{sceneTypes.map(value=><option key={value} value={value}>{label(value)}</option>)}</select></label><label className="scene-edit-speaker">Personagem<select aria-label="Personagem" value={draft.speaker} onChange={e=>setSpeaker(e.target.value)}>{speakers.map(([value,text])=><option key={value} value={value}>{text}</option>)}</select></label><label className="scene-edit-purpose">Propósito<select aria-label="Propósito" value={draft.purpose} onChange={e=>set('purpose',e.target.value)}>{purposes.map(value=><option key={value} value={value}>{label(value)}</option>)}</select></label><label className="scene-edit-narration">Narração<textarea rows={4} value={draft.narrationText} onChange={e=>set('narrationText',e.target.value)}/></label><label className="scene-edit-screen">Texto na tela<textarea rows={3} value={draft.onScreenText} onChange={e=>set('onScreenText',e.target.value)}/></label><label className="scene-edit-visual">Instrução visual<textarea rows={3} value={draft.visualInstruction} onChange={e=>set('visualInstruction',e.target.value)}/></label>{usesAvatar(draft.speaker)&&<label className="scene-edit-avatar">Expressão<select aria-label="Expressão" value={draft.avatarState} onChange={e=>set('avatarState',e.target.value)}>{avatarStates[draft.speaker].map(([value,text])=><option key={value} value={value}>{text}</option>)}</select></label>}<label className="scene-edit-duration">Duração em segundos<input aria-label="Duração em segundos" type="number" min="1" value={draft.durationSeconds} onChange={e=>set('durationSeconds',e.target.value)}/></label><div className="scene-edit-actions"><button type="button" className="ghost-button small" disabled={saving} onClick={cancel}>Cancelar</button><button type="button" className="primary-button small" disabled={saving} onClick={save}>{saving?'Salvando…':'Salvar'}</button></div>{error&&<p role="alert" className="inline-error">{error}</p>}</div>;
  return <div><span><b>{index+1}. {label(scene.sceneType)} · {label(scene.speaker)}</b><small>{label(scene.purpose)} — {scene.narrationText||'Sem narração'}</small></span>{editable&&<div className="actions"><button type="button" onClick={()=>{setDraft(draftFrom(scene));setError('');setEditing(true)}}>Editar</button><button type="button" disabled={index===0} onClick={async()=>{await creativesApi.patchScene(creativeId,scene.id,{orderIndex:scene.orderIndex-1});onRefresh()}}>↑</button><button type="button" disabled={index===count-1} onClick={async()=>{await creativesApi.patchScene(creativeId,scene.id,{orderIndex:scene.orderIndex+1});onRefresh()}}>↓</button><button type="button" onClick={async()=>{await creativesApi.removeScene(creativeId,scene.id);onRefresh()}}>Excluir</button></div>}</div>;
}
