import{useCallback,useEffect,useRef,useState}from'react';
import{mediaApi}from'../api/media';
import type{MediaAsset,MediaDiagnostics,MediaJob}from'../types';
import{Badge}from'./ui';

const terminal=new Set(['COMPLETED','FAILED','CANCELED']);
const running=new Set(['PREPARING','RENDERING_AUDIO','RENDERING_SCENES','COMPOSING','VALIDATING']);
const statuses:Record<string,string>={QUEUED:'Na fila',PREPARING:'Preparando',RENDERING_AUDIO:'Gerando áudio',RENDERING_SCENES:'Renderizando cenas',COMPOSING:'Montando vídeo',VALIDATING:'Validando vídeo',COMPLETED:'Concluído',FAILED:'Falhou',CANCELED:'Cancelado'};
const assetLabels:Record<string,string>={PRODUCT_IMAGE:'Imagem do produto',AVATAR_IMAGE:'Avatar',LOGO:'Marca'};
const statusLabel=(value:string|null)=>statuses[value??'']??'Aguardando';
const tone=(value:string)=>value==='COMPLETED'?'success':value==='FAILED'?'danger':value==='CANCELED'?'warning':'info';
const date=(value:string|null)=>value?new Intl.DateTimeFormat('pt-BR',{dateStyle:'short',timeStyle:'short'}).format(new Date(value)):'—';
const duration=(job:MediaJob)=>{const validated=job.validationDetails?.durationSeconds;return typeof validated==='number'?validated:job.actualDurationSeconds};
const size=(bytes:number|null)=>bytes==null?'—':`${(bytes/1024/1024).toFixed(1)} MB`;
const friendlyDiagnostic=(item:{status:string}|undefined,voice=false)=>item?.status==='AVAILABLE'?'Disponível':item?.status==='NOT_CONFIGURED'?(voice?'Não configurada':'Indisponível'):'Erro';

export function MediaProduction({creativeId,candidateId,requiresVoice=false}:{creativeId:string;candidateId:string;requiresVoice?:boolean}){
  const[jobs,setJobs]=useState<MediaJob[]>([]),[assets,setAssets]=useState<MediaAsset[]>([]),[diagnostics,setDiagnostics]=useState<MediaDiagnostics|null>(null),[currentId,setCurrentId]=useState<string|null>(null),[removingId,setRemovingId]=useState<string|null>(null),[busy,setBusy]=useState(false),[error,setError]=useState('');
  const generating=useRef(false);
  const load=useCallback(async()=>{const[j,a,d]=await Promise.all([mediaApi.jobs(creativeId),mediaApi.assets(candidateId),mediaApi.diagnostics()]);setJobs(Array.isArray(j)?j:[]);setAssets(Array.isArray(a)?a:[]);setDiagnostics(d&&typeof d==='object'?d:null);const active=(Array.isArray(j)?j:[]).find(x=>running.has(x.status));setCurrentId(active?.id??null)},[creativeId,candidateId]);
  useEffect(()=>{load().catch(e=>setError(e instanceof Error?e.message:'Não foi possível carregar a produção de mídia.'))},[load]);
  useEffect(()=>{if(!currentId)return;const timer=window.setInterval(async()=>{try{const updated=await mediaApi.job(currentId);setJobs(old=>[updated,...old.filter(x=>x.id!==updated.id)]);if(terminal.has(updated.status))setCurrentId(null)}catch(e){setError(e instanceof Error?e.message:'Não foi possível atualizar o andamento.');setCurrentId(null)}},1500);return()=>window.clearInterval(timer)},[currentId]);
  const available=(value:MediaDiagnostics|null)=>Boolean(value&&value.storage.status==='AVAILABLE'&&value.ffmpeg.status==='AVAILABLE'&&value.ffprobe.status==='AVAILABLE'&&(!requiresVoice||value.tts.status==='AVAILABLE'));
  const generate=async(renderType:'PREVIEW'|'STANDARD')=>{if(generating.current)return;generating.current=true;setBusy(true);setError('');try{const fresh=await mediaApi.diagnostics();setDiagnostics(fresh);if(!available(fresh)){setError('Produção de mídia indisponível. Verifique a configuração local de vídeo e voz.');return}const created=await mediaApi.create(creativeId,renderType);setJobs(old=>[created,...old.filter(x=>x.id!==created.id)]);try{const started=await mediaApi.start(created.id);setJobs(old=>[started,...old.filter(x=>x.id!==started.id)]);if(running.has(started.status))setCurrentId(started.id)}catch(startError){setError(startError instanceof Error?`O job foi criado, mas não pôde ser iniciado: ${startError.message}`:'O job foi criado, mas não pôde ser iniciado. Cancele-o para tentar novamente.')}}catch(e){setError(e instanceof Error?e.message:'Não foi possível iniciar a produção.')}finally{generating.current=false;setBusy(false)}};
  const latest=jobs[0],activeJob=jobs.find(x=>!terminal.has(x.status));const hasVisual=assets.some(x=>x.active&&['PRODUCT_IMAGE','AVATAR_IMAGE','LOGO'].includes(x.assetType)),mediaAvailable=available(diagnostics);
  return <>
    <section className="panel media-production"><div className="panel-head"><h2>Produção de mídia</h2><div className="media-actions"><button type="button" className="primary-button" disabled={busy||Boolean(activeJob)||!mediaAvailable} onClick={()=>generate('PREVIEW')}>Gerar preview</button><button type="button" className="ghost-button" disabled={busy||Boolean(activeJob)||!mediaAvailable} onClick={()=>generate('STANDARD')}>Gerar vídeo final</button></div></div>
      {diagnostics&&!mediaAvailable&&<p className="media-notice">Produção de mídia indisponível. Verifique a configuração local de vídeo e voz.</p>}
      {!hasVisual&&<p className="media-notice">O vídeo será gerado com layout padrão porque ainda não há imagem do produto ou avatar disponível.</p>}
      {error&&<p role="alert" className="inline-error">{error}</p>}
      {latest?<div className="media-current"><div><small>Última produção</small><b>{latest.renderType==='PREVIEW'?'Preview':'Vídeo final'}</b></div><Badge tone={tone(latest.status)}>{statusLabel(latest.status)}</Badge><div><small>Etapa</small><b>{statusLabel(latest.currentStage)}</b></div><div><small>Criado em</small><b>{date(latest.createdAt)}</b></div><div className="media-progress"><div className="progress"><i style={{width:`${latest.progressPercent}%`}}/></div><span>{latest.progressPercent}%{latest.totalScenes!=null&&latest.currentSceneIndex!=null?` · Cena ${Math.min(latest.currentSceneIndex+1,latest.totalScenes)} de ${latest.totalScenes}`:''}</span></div></div>:<p className="empty">Nenhum vídeo produzido para este criativo.</p>}
      {latest?.status==='FAILED'&&<div className="media-failure"><p>{latest.errorMessage||'Não foi possível concluir a produção do vídeo.'}</p><button type="button" className="ghost-button" disabled={busy} onClick={()=>generate(latest.renderType)}>Tentar novamente</button></div>}
      {latest?.status==='QUEUED'&&<div className="media-failure"><p>Este job ainda não foi iniciado. Cancele-o para liberar uma nova tentativa.</p><button type="button" className="ghost-button" onClick={async()=>{try{const canceled=await mediaApi.cancel(latest.id);setJobs(old=>[canceled,...old.filter(x=>x.id!==canceled.id)]);setCurrentId(null)}catch(e){setError(e instanceof Error?e.message:'Não foi possível cancelar o job.')}}}>Cancelar job</button></div>}
      {latest?.status==='COMPLETED'&&latest.validationStatus==='VALID'&&<div className="media-result"><video controls preload="metadata" src={mediaApi.contentUrl(latest.id)}>Seu navegador não suporta reprodução de vídeo.</video><a className="ghost-button" href={mediaApi.contentUrl(latest.id,true)}>Baixar vídeo</a></div>}
    </section>
    <section className="panel media-assets"><div className="panel-head"><h2>Imagens</h2></div><form onSubmit={async e=>{e.preventDefault();setError('');const formElement=e.currentTarget;const data=new FormData(formElement),type=String(data.get('assetType'));data.set('ownerType',type==='PRODUCT_IMAGE'?'CANDIDATE':type==='AVATAR_IMAGE'?'AVATAR':'BRAND');data.set('ownerId',candidateId);data.set('logicalName',(data.get('file')as File)?.name||'Imagem');try{const uploaded=await mediaApi.upload(data);setAssets(old=>[uploaded,...old]);formElement.reset()}catch(err){setError(err instanceof Error?err.message:'Não foi possível enviar a imagem.')}}}><label>Tipo<select name="assetType"><option value="PRODUCT_IMAGE">Imagem do produto</option><option value="AVATAR_IMAGE">Avatar</option><option value="LOGO">Marca</option></select></label><label>Arquivo<input name="file" type="file" accept="image/png,image/jpeg,image/webp" required/></label><button type="submit" className="ghost-button">Enviar imagem</button></form><div className="asset-grid">{assets.map(asset=><article className="asset-card" key={asset.id}>{asset.active?<img src={mediaApi.assetUrl(asset.id)} alt=""/>:<span className="asset-placeholder">Imagem inativa</span>}<div><b>{asset.logicalName}</b><small>{assetLabels[asset.assetType]??'Imagem'}</small><strong className={asset.active?'asset-status active':'asset-status'}>{asset.active?'Ativo':'Inativo'}</strong></div><div className="asset-card-actions"><button type="button" className="ghost-button small" onClick={async()=>{try{const updated=asset.active?await mediaApi.removeAsset(asset.id):await mediaApi.activateAsset(asset.id);setAssets(old=>old.map(x=>x.id===updated.id?updated:x))}catch(err){setError(err instanceof Error?err.message:`Não foi possível ${asset.active?'desativar':'ativar'} a imagem.`)}}}>{asset.active?'Desativar':'Ativar'}</button><button type="button" className="danger-button small" onClick={()=>setRemovingId(asset.id)}>Remover</button></div>{removingId===asset.id&&<div className="asset-remove-confirm" role="alertdialog" aria-label="Confirmar remoção"><p>Remover esta imagem permanentemente?</p><button type="button" className="ghost-button small" onClick={()=>setRemovingId(null)}>Cancelar</button><button type="button" className="danger-button small" onClick={async()=>{try{await mediaApi.deleteAsset(asset.id);setAssets(old=>old.filter(x=>x.id!==asset.id));setRemovingId(null)}catch(err){setError(err instanceof Error?err.message:'Não foi possível remover a imagem.')}}}>Remover</button></div>}</article>)}</div></section>
    <section className="panel media-diagnostics"><details><summary>Diagnóstico de mídia</summary><div className="diagnostic-friendly">{[['FFmpeg',friendlyDiagnostic(diagnostics?.ffmpeg)],['FFprobe',friendlyDiagnostic(diagnostics?.ffprobe)],['Voz',friendlyDiagnostic(diagnostics?.tts,true)],['Armazenamento',friendlyDiagnostic(diagnostics?.storage)]].map(([name,value])=><div key={name}><span>{name}</span><b>{value}</b></div>)}</div></details></section>
    <section className="panel media-history"><div className="panel-head"><h2>Histórico de produção</h2></div>{jobs.length?<div className="table-wrap"><table><thead><tr><th>Tipo</th><th>Status</th><th>Criado</th><th>Concluído</th><th>Duração</th><th>Tamanho</th></tr></thead><tbody>{jobs.map(job=><tr key={job.id}><td>{job.renderType==='PREVIEW'?'Preview':'Vídeo final'}</td><td><Badge tone={tone(job.status)}>{statusLabel(job.status)}</Badge></td><td>{date(job.createdAt)}</td><td>{date(job.completedAt)}</td><td>{duration(job)!=null?`${duration(job)} s`:'—'}</td><td>{size(job.outputSizeBytes)}</td></tr>)}</tbody></table></div>:<p className="empty">O histórico aparecerá após a primeira produção.</p>}</section>
  </>;
}
