import{useCallback,useEffect,useRef,useState}from'react';
import type{FormEvent}from'react';
import{Link}from'react-router-dom';
import{mediaApi}from'../api/media';
import type{MediaAsset,MediaDiagnostics,MediaHandoffState,MediaJob,ProductMediaBundle,ProductMediaState,ProductMediaSyncResponse}from'../types';
import{Badge}from'./ui';
import{label}from'../lib/presentation';
import{ApiRequestError}from'../lib/apiError';

const terminal=new Set(['COMPLETED','FAILED','CANCELED']);
const running=new Set(['PREPARING','RENDERING_AUDIO','RENDERING_SCENES','COMPOSING','VALIDATING']);
const assetLabels:Record<string,string>={PRODUCT_IMAGE:'Imagem do produto',PRODUCT_VIDEO:'Vídeo do produto',AVATAR_IMAGE:'Avatar',LOGO:'Marca'};
const classificationLabels:Record<string,string>={HERO_IMAGE:'Imagem principal',ALTERNATE_IMAGE:'Imagem alternativa',DETAIL_IMAGE:'Detalhe',ACCESSORY_IMAGE:'Acessório',PACKAGE_IMAGE:'Embalagem',CONTEXT_IMAGE:'Contexto',FEATURE_IMAGE:'Recurso',VIDEO_CLIP:'Clipe de vídeo',UNKNOWN_PRODUCT_MEDIA:'Não classificada'};
const classificationOptions=Object.entries(classificationLabels);
const diversityLabels:Record<string,string>={LOW:'Baixa',MEDIUM:'Média',HIGH:'Alta'};
const avatarStates:Record<string,[string,string][]>= {BRUNO:[['NEUTRAL','Neutro'],['EXPLAINING','Explicando'],['APPROVING','Aprovando'],['WARNING','Alerta'],['QUESTIONING','Questionando'],['POINTING','Apontando'],['COMPARING','Comparando']],CAROL:[['NEUTRAL','Neutro'],['CURIOUS','Curiosa'],['APPROVING','Aprovando'],['WARNING','Alerta'],['QUESTIONING','Questionando'],['AGREEING','Concordando'],['THINKING','Pensando']]};
const statusLabel=(value:string|null)=>value?label(value):'Aguardando';
const tone=(value:string)=>value==='COMPLETED'?'success':value==='FAILED'?'danger':value==='CANCELED'?'warning':'info';
const date=(value:string|null)=>value?new Intl.DateTimeFormat('pt-BR',{dateStyle:'short',timeStyle:'short'}).format(new Date(value)):'—';
const duration=(job:MediaJob)=>{const validated=job.validationDetails?.durationSeconds;return typeof validated==='number'?validated:job.actualDurationSeconds};
const size=(bytes:number|null)=>bytes==null?'—':`${(bytes/1024/1024).toFixed(1)} MB`;
const friendlyDiagnostic=(item:{status:string}|undefined,voice=false)=>item?.status==='AVAILABLE'?'Disponível':item?.status==='NOT_CONFIGURED'?(voice?'Não configurada':'Indisponível'):'Erro';
type ProductVisualReadiness={activeImageCount:number;usableImageCount:number;uniqueVisualGroups:number;state:'READY'|'LIMITED'|'EMPTY'};

export function MediaProduction({creativeId,candidateId}:{creativeId:string;candidateId:string;requiresVoice?:boolean}){
  const[jobs,setJobs]=useState<MediaJob[]>([]),[diagnostics,setDiagnostics]=useState<MediaDiagnostics|null>(null),[handoff,setHandoff]=useState<MediaHandoffState|null>(null),[renderType,setRenderType]=useState<'PREVIEW'|'STANDARD'>('PREVIEW'),[currentId,setCurrentId]=useState<string|null>(null),[busy,setBusy]=useState(false),[confirmStart,setConfirmStart]=useState(false),[confirmCancel,setConfirmCancel]=useState(false),[error,setError]=useState('');
  const[visualReadiness,setVisualReadiness]=useState<ProductVisualReadiness|null>(null);
  const actionLock=useRef(false);
  const updateVisualReadiness=useCallback((value:ProductVisualReadiness)=>setVisualReadiness(value),[]);
  const load=useCallback(async()=>{const[j,h,d]=await Promise.all([mediaApi.jobs(creativeId),mediaApi.handoff(creativeId,renderType),mediaApi.diagnostics().catch(()=>null)]);const ordered=(Array.isArray(j)?j:[]).sort((x,y)=>Date.parse(y.createdAt)-Date.parse(x.createdAt));setJobs(ordered);setHandoff(h);setDiagnostics(d&&typeof d==='object'?d:null);const linked=h.mediaJobId?ordered.find(x=>x.id===h.mediaJobId):null;setCurrentId(linked&&running.has(linked.status)?linked.id:null)},[creativeId,renderType]);
  useEffect(()=>{load().catch(e=>setError(e instanceof Error?e.message:'Não foi possível carregar a produção de mídia.'))},[load]);
  useEffect(()=>{if(!currentId)return;const timer=window.setInterval(async()=>{try{const updated=await mediaApi.job(currentId);setJobs(old=>[updated,...old.filter(x=>x.id!==updated.id)].sort((x,y)=>Date.parse(y.createdAt)-Date.parse(x.createdAt)));if(terminal.has(updated.status)){setCurrentId(null);await load()}}catch(e){setError(e instanceof Error?e.message:'Não foi possível atualizar o andamento.');setCurrentId(null)}},1500);return()=>window.clearInterval(timer)},[currentId,load]);
  const runAction=async(action:()=>Promise<void>)=>{if(actionLock.current)return;actionLock.current=true;setBusy(true);setError('');try{await action()}finally{actionLock.current=false;setBusy(false)}};
  const prepare=()=>runAction(async()=>{if(handoff?.state!=='READY_TO_CREATE')return;try{const created=await mediaApi.create(creativeId,renderType);setJobs(old=>[created,...old.filter(x=>x.id!==created.id)]);await load().catch(()=>setError('A produção foi preparada, mas não foi possível atualizar o estado. Atualize a página.'))}catch(e){setError(e instanceof Error?e.message:'Não foi possível preparar a produção.')}});
  const start=()=>runAction(async()=>{const job=handoff?.mediaJobId?jobs.find(x=>x.id===handoff.mediaJobId):null;if(!job||job.status!=='QUEUED')return;setConfirmStart(false);try{const started=await mediaApi.start(job.id);setJobs(old=>[started,...old.filter(x=>x.id!==started.id)]);if(running.has(started.status))setCurrentId(started.id);await load().catch(()=>setError('A renderização foi iniciada, mas não foi possível atualizar o estado. Atualize a página.'))}catch(e){setError(e instanceof ApiRequestError&&e.code==='MEDIA_JOB_INPUT_STALE'?'As fontes visuais foram alteradas depois que esta produção foi preparada. Prepare uma nova produção.':'Não foi possível iniciar a produção. Verifique a configuração local de vídeo e voz.');await load().catch(()=>undefined)}});
  const cancel=()=>runAction(async()=>{const job=handoff?.mediaJobId?jobs.find(x=>x.id===handoff.mediaJobId):null;if(!job||job.status!=='QUEUED')return;setConfirmCancel(false);try{const canceled=await mediaApi.cancel(job.id);setJobs(old=>[canceled,...old.filter(x=>x.id!==canceled.id)]);setCurrentId(null);await load().catch(()=>setError('A produção foi cancelada, mas não foi possível atualizar o estado. Atualize a página.'))}catch(e){setError(e instanceof Error?e.message:'Não foi possível cancelar a produção.')}});
  const activeHandoffJob=handoff?.mediaJobId?jobs.find(x=>x.id===handoff.mediaJobId):undefined;
  const latest=handoff?.state==='MULTIPLE_ACTIVE_JOBS'?undefined:activeHandoffJob??jobs.find(x=>x.renderType===renderType);
  const jobProfile=(job:MediaJob)=>job.renderType==='PREVIEW'?'Preview':'Vídeo final';
  const jobDimensions=(job:MediaJob)=>`${job.width} × ${job.height}`;
  const reasonMessages:Record<string,string>={CREATIVE_NOT_APPROVED:'O criativo precisa estar aprovado para produzir mídia.',VIDEO_RENDER_NOT_ELIGIBLE:'Este formato de criativo não é elegível para produção de vídeo.',CREATIVE_APPROVAL_REQUIRED:'A aprovação do criativo precisa estar registrada para preparar a produção.',CREATIVE_APPROVAL_STATE_INCONSISTENT:'O histórico de aprovação do criativo precisa ser revisado.',MEDIA_HANDOFF_INVALIDATED:'O conteúdo mudou ou possui pendências que impedem preparar a produção.'};
  const renderProgress=(job:MediaJob)=><div className="media-progress" aria-label="Progresso da renderização"><div className="progress"><i style={{width:`${job.progressPercent}%`}}/></div><span>{job.progressPercent}%{job.totalScenes!=null&&job.currentSceneIndex!=null?` · Cena ${Math.min(job.currentSceneIndex+1,job.totalScenes)} de ${job.totalScenes}`:''}</span></div>;
  return <>
    <MediaAssetsPanel candidateId={candidateId} onReadinessChange={updateVisualReadiness}/>
    <section className="panel media-production" aria-labelledby="media-next-action-title"><div className="panel-head"><h2 id="media-next-action-title">Próxima ação</h2></div>
      <div className="media-source-readiness" aria-live="polite"><div><b>Fontes visuais</b><span>{visualReadiness?`${visualReadiness.usableImageCount} ${visualReadiness.usableImageCount===1?'imagem disponível':'imagens disponíveis'}`:'Carregando imagens…'}</span></div><Badge tone={!visualReadiness||visualReadiness.state==='EMPTY'?'warning':visualReadiness.state==='READY'?'success':'warning'}>{!visualReadiness?'Carregando':visualReadiness.state==='EMPTY'?'Sem imagens':visualReadiness.state==='READY'?'Pronto':'Limitado'}</Badge><p>{!visualReadiness?'':visualReadiness.state==='EMPTY'?'Nenhuma imagem utilizável está disponível. Atualize os dados do Mercado Livre na Curadoria ou adicione uma imagem local.':visualReadiness.state==='LIMITED'?'Material visual limitado — o vídeo poderá repetir imagens.':'Há diversidade visual suficiente para produzir o vídeo.'}</p></div>
      <fieldset className="media-profile-picker"><legend>Perfil de produção</legend><label className={renderType==='PREVIEW'?'selected':''}><input type="radio" name="renderType" value="PREVIEW" checked={renderType==='PREVIEW'} onChange={()=>{setHandoff(null);setConfirmStart(false);setConfirmCancel(false);setRenderType('PREVIEW')}}/><span><b>Preview</b><small>540 × 960</small></span></label><label className={renderType==='STANDARD'?'selected':''}><input type="radio" name="renderType" value="STANDARD" checked={renderType==='STANDARD'} onChange={()=>{setHandoff(null);setConfirmStart(false);setConfirmCancel(false);setRenderType('STANDARD')}}/><span><b>Vídeo final</b><small>1080 × 1920</small></span></label></fieldset>
      {error&&<p role="alert" className="inline-error">{error}</p>}
      {!handoff?<p className="empty" role="status">Carregando o estado da produção…</p>:handoff.state==='READY_TO_CREATE'?<div className="media-handoff-state" aria-live="polite">
        <h3>{latest?.status==='COMPLETED'&&latest.validationStatus==='VALID'?'Produção concluída':latest?.status==='FAILED'?'Não foi possível concluir a produção':latest?.status==='CANCELED'?'Produção cancelada':'Produção pronta para ser preparada'}</h3>
        {latest&&terminal.has(latest.status)&&<p>Último resultado: {jobProfile(latest)} · tentativa {latest.attemptNumber} · {statusLabel(latest.status)}{latest.status==='FAILED'&&latest.errorMessage?` — ${latest.errorMessage}`:''}</p>}
        <p>Esta ação apenas cria a tentativa de produção. A renderização não será iniciada.</p>
        <button type="button" className={latest&&terminal.has(latest.status)?'ghost-button':'primary-button'} disabled={busy} onClick={()=>void prepare()}>{busy?'Preparando…':latest&&terminal.has(latest.status)?'Preparar nova tentativa':renderType==='PREVIEW'?'Preparar preview':'Preparar vídeo final'}</button>
      </div>:handoff.state==='NOT_ELIGIBLE'?<div className="media-handoff-state" role="status"><h3>Produção indisponível</h3><p>{reasonMessages[handoff.reasonCode??'']??'A produção não está disponível com o estado atual do criativo.'}</p>{handoff.blockers.map((blocker,index)=><p key={`${blocker.code}-${index}`}>{blocker.message}</p>)}{handoff.warnings.map((warning,index)=><p className="muted" key={`${warning.code}-${index}`}>{warning.message}</p>)}<Link className="ghost-button" to={`/criativos/${creativeId}`}>Voltar ao criativo</Link></div>:handoff.state==='MULTIPLE_ACTIVE_JOBS'?<div className="media-handoff-state" role="alert"><h3>Encontramos mais de uma produção ativa</h3><p>Atualize a página. Se o problema continuar, revise o histórico técnico.</p></div>:handoff.state==='ACTIVE_JOB_CONFLICT'?<div className="media-handoff-state" role="status"><h3>Já existe uma produção ativa para este criativo</h3>{activeHandoffJob&&<p>{jobProfile(activeHandoffJob)} · {statusLabel(activeHandoffJob.status)} · tentativa {activeHandoffJob.attemptNumber}</p>}<p>Conclua ou cancele a produção atual antes de preparar outro perfil.</p>{activeHandoffJob&&activeHandoffJob.renderType!==renderType&&<button type="button" className="ghost-button" onClick={()=>setRenderType(activeHandoffJob.renderType)}>Ver produção ativa</button>}</div>:<div className="media-handoff-state" aria-live="polite">
        {handoff.mediaJobStatus==='QUEUED'&&activeHandoffJob?<><h3>Produção preparada</h3><p>A produção está preparada, mas ainda não foi iniciada.</p><div className="media-job-facts"><span>Tipo<b>{jobProfile(activeHandoffJob)}</b></span><span>Tentativa<b>{activeHandoffJob.attemptNumber}</b></span><span>Dimensões<b>{jobDimensions(activeHandoffJob)}</b></span><span>Criada em<b>{date(activeHandoffJob.createdAt)}</b></span><span>Origem<b>{label(activeHandoffJob.creationSource)}</b></span></div>
          {!confirmStart?<button type="button" className="primary-button" disabled={busy} onClick={()=>setConfirmStart(true)}>Iniciar renderização</button>:<div className="media-inline-confirm" role="group" aria-label="Confirmar início da renderização"><p><b>Iniciar a renderização agora?</b><br/>O pipeline de vídeo e voz poderá ser executado.</p><button type="button" className="ghost-button" disabled={busy} onClick={()=>setConfirmStart(false)}>Cancelar</button><button type="button" className="primary-button" disabled={busy} onClick={()=>void start()}>{busy?'Iniciando…':'Confirmar início'}</button></div>}
          {!confirmCancel?<button type="button" className="ghost-button" disabled={busy} onClick={()=>setConfirmCancel(true)}>Cancelar produção</button>:<div className="media-inline-confirm" role="group" aria-label="Confirmar cancelamento da produção"><p>Cancelar esta produção?</p><button type="button" className="ghost-button" disabled={busy} onClick={()=>setConfirmCancel(false)}>Voltar</button><button type="button" className="danger-button" disabled={busy} onClick={()=>void cancel()}>{busy?'Cancelando…':'Confirmar cancelamento'}</button></div>}</>:activeHandoffJob&&running.has(activeHandoffJob.status)?<><h3>Renderização em andamento</h3><div className="media-current"><div><small>Tipo</small><b>{jobProfile(activeHandoffJob)}</b></div><Badge tone={tone(activeHandoffJob.status)}>{statusLabel(activeHandoffJob.status)}</Badge><div><small>Etapa atual</small><b>{statusLabel(activeHandoffJob.currentStage)}</b></div><div><small>Tentativa</small><b>{activeHandoffJob.attemptNumber}</b></div>{renderProgress(activeHandoffJob)}</div></>:<><h3>Produção já preparada</h3><p>O estado atual impede outra preparação até que a produção existente seja resolvida.</p></>}
      </div>}
      {latest?.status==='COMPLETED'&&latest.validationStatus==='VALID'&&<div className="media-result"><h3>Resultado</h3><div className="media-job-facts"><span>Tipo<b>{jobProfile(latest)}</b></span><span>Tentativa<b>{latest.attemptNumber}</b></span><span>Duração<b>{duration(latest)!=null?`${duration(latest)} s`:'—'}</b></span><span>Tamanho<b>{size(latest.outputSizeBytes)}</b></span><span>Concluída<b>{date(latest.completedAt)}</b></span></div><video controls preload="metadata" src={mediaApi.contentUrl(latest.id)}>Seu navegador não suporta reprodução de vídeo.</video><a className="ghost-button" href={mediaApi.contentUrl(latest.id,true)}>Baixar vídeo</a></div>}
      {latest?.previousMediaJobId&&<details className="media-technical"><summary>Detalhes técnicos</summary><p>Nova tentativa da produção anterior.</p><code>{latest.id}</code><code>{latest.previousMediaJobId}</code>{latest.creationKey&&<code>{latest.creationKey}</code>}{latest.inputFingerprint&&<code>{latest.inputFingerprint}</code>}</details>}
    </section>
    <section className="panel media-diagnostics"><details><summary>Diagnóstico técnico</summary><p className="muted">Informativo. A verificação final ocorre ao iniciar a renderização.</p><div className="diagnostic-friendly">{[['FFmpeg',friendlyDiagnostic(diagnostics?.ffmpeg)],['FFprobe',friendlyDiagnostic(diagnostics?.ffprobe)],['Voz',friendlyDiagnostic(diagnostics?.tts,true)],['Armazenamento',friendlyDiagnostic(diagnostics?.storage)]].map(([name,value])=><div key={name}><span>{name}</span><b>{value}</b></div>)}</div></details></section>
    <section className="panel media-history"><div className="panel-head"><h2>Histórico de produção</h2></div>{jobs.length?<div className="media-history-list">{jobs.map(job=><article key={job.id} className="media-history-card"><div><small>Tipo</small><b>{jobProfile(job)}</b></div><div><small>Status</small><Badge tone={tone(job.status)}>{statusLabel(job.status)}</Badge></div><div><small>Tentativa</small><b>{job.attemptNumber}</b></div><div><small>Criada</small><b>{date(job.createdAt)}</b></div><div><small>Iniciada</small><b>{date(job.startedAt)}</b></div><div><small>Concluída</small><b>{date(job.completedAt)}</b></div><div><small>Duração</small><b>{duration(job)!=null?`${duration(job)} s`:'—'}</b></div><div><small>Tamanho</small><b>{size(job.outputSizeBytes)}</b></div><details><summary>Detalhes técnicos</summary><code>{job.id}</code>{job.inputFingerprint&&<code>{job.inputFingerprint}</code>}{job.creationKey&&<code>{job.creationKey}</code>}{job.previousMediaJobId&&<p>Nova tentativa da produção anterior: <code>{job.previousMediaJobId}</code></p>}</details></article>)}</div>:<p className="empty">O histórico aparecerá após a primeira produção.</p>}</section>
  </>;
}

function MediaAssetsPanel({candidateId,onReadinessChange}:{candidateId:string;onReadinessChange:(value:ProductVisualReadiness)=>void}){
  const[assets,setAssets]=useState<MediaAsset[]>([]),[bundle,setBundle]=useState<ProductMediaBundle|null>(null),[productMedia,setProductMedia]=useState<ProductMediaState|null>(null),[syncResult,setSyncResult]=useState<ProductMediaSyncResponse|null>(null),[loading,setLoading]=useState(true),[syncing,setSyncing]=useState(false),[updatingId,setUpdatingId]=useState<string|null>(null),[removingId,setRemovingId]=useState<string|null>(null),[error,setError]=useState(''),[assetType,setAssetType]=useState('PRODUCT_IMAGE'),[character,setCharacter]=useState('BRUNO'),[classification,setClassification]=useState('UNKNOWN_PRODUCT_MEDIA');
  const syncLock=useRef(false);
  const load=useCallback(async()=>{const[all,current,b]=await Promise.all([mediaApi.assets(candidateId),mediaApi.candidateProductMedia(candidateId).catch(()=>null),mediaApi.productBundle(candidateId).catch(()=>null)]);setAssets(all);setProductMedia(current);setBundle(b&&Array.isArray(b.assets)?b:null);setLoading(false)},[candidateId]);
  useEffect(()=>{let mounted=true;void load().catch(()=>{if(mounted){setError('Não foi possível carregar as fontes visuais.');setLoading(false)}});return()=>{mounted=false}},[load]);
  const isMarketplaceImage=(asset:MediaAsset)=>asset.metadata?.provider==='MERCADO_LIVRE'||asset.metadata?.sourceKind==='MERCADO_LIVRE_OFFICIAL_API';
  const productImages=assets.filter(asset=>asset.ownerType==='CANDIDATE'&&asset.ownerId===candidateId&&asset.assetType==='PRODUCT_IMAGE').sort((left,right)=>{
    if(left.active!==right.active)return left.active?-1:1;
    const rank=(asset:MediaAsset)=>asset.metadata?.classification==='HERO_IMAGE'?0:isMarketplaceImage(asset)&&typeof asset.metadata?.position==='number'?1:isMarketplaceImage(asset)?2:3;
    const rankDifference=rank(left)-rank(right);if(rankDifference)return rankDifference;
    if(isMarketplaceImage(left)&&isMarketplaceImage(right)){const positionDifference=(left.metadata?.position??Number.MAX_SAFE_INTEGER)-(right.metadata?.position??Number.MAX_SAFE_INTEGER);if(positionDifference)return positionDifference;}
    return left.logicalName.localeCompare(right.logicalName,'pt-BR');
  });
  const activeImages=productImages.filter(asset=>asset.active);
  const inactiveImages=productImages.filter(asset=>!asset.active);
  const usableImages=activeImages.filter(asset=>{const analyzed=bundle?.assets.find(item=>item.assetId===asset.id);return !bundle||(analyzed!==undefined&&!analyzed.warnings.includes('FILE_MISSING'))});
  const uniqueVisualGroups=bundle?.uniqueVisualGroups??usableImages.length;
  useEffect(()=>{onReadinessChange({activeImageCount:activeImages.length,usableImageCount:usableImages.length,uniqueVisualGroups,state:usableImages.length===0?'EMPTY':uniqueVisualGroups>=3?'READY':'LIMITED'})},[activeImages.length,usableImages.length,uniqueVisualGroups,onReadinessChange]);
  const refreshBundle=async()=>{try{setBundle(await mediaApi.productBundle(candidateId))}catch{setError('A mídia foi atualizada, mas não foi possível atualizar o resumo visual.')}};
  const friendlyMediaError=(code:string)=>({PRODUCT_MEDIA_SOURCE_NOT_FOUND:'Não encontramos fotos oficiais para este produto.',PRODUCT_MEDIA_SOURCE_NOT_OFFICIAL:'Não encontramos fotos oficiais verificáveis para este produto.',PRODUCT_MEDIA_DOWNLOAD_FAILED:'Não foi possível baixar uma ou mais imagens.',PRODUCT_MEDIA_INVALID_CONTENT:'Uma das imagens recebidas não era válida.',PRODUCT_MEDIA_UNSUPPORTED_TYPE:'Uma das imagens recebidas usa um formato não compatível.',PRODUCT_MEDIA_REMOTE_HOST_NOT_ALLOWED:'Uma imagem foi recusada por segurança.',PRODUCT_MEDIA_TOO_LARGE:'Uma das imagens excede o tamanho permitido.'}[code]??'Não foi possível sincronizar as fotos do produto.');
  const sync=async()=>{if(syncLock.current)return;syncLock.current=true;setSyncing(true);setError('');setSyncResult(null);try{const result=await mediaApi.syncCandidateProductMedia(candidateId);setSyncResult(result);if(!(result.status==='UNAVAILABLE'&&result.reasonCode==='PRODUCT_MEDIA_SOURCE_NOT_FOUND'))await load();}catch(e){setError(e instanceof Error?e.message:'Não foi possível sincronizar as fotos do Mercado Livre.')}finally{syncLock.current=false;setSyncing(false)}};
  const upload=async(event:FormEvent<HTMLFormElement>)=>{event.preventDefault();setError('');const form=event.currentTarget,data=new FormData(form),type=String(data.get('assetType')),isProduct=type==='PRODUCT_IMAGE'||type==='PRODUCT_VIDEO';data.set('ownerType',isProduct?'CANDIDATE':type==='AVATAR_IMAGE'?'AVATAR':'BRAND');data.set('ownerId',type==='AVATAR_IMAGE'?String(data.get('character')):candidateId);data.set('logicalName',(data.get('file')as File)?.name||'Mídia');try{const added=await mediaApi.upload(data);setAssets(old=>[added,...old]);if(isProduct)await refreshBundle();form.reset();setAssetType('PRODUCT_IMAGE');setCharacter('BRUNO');setClassification('UNKNOWN_PRODUCT_MEDIA')}catch(e){setError(e instanceof Error?e.message:'Não foi possível enviar a mídia.')}};
  const toggle=async(asset:MediaAsset)=>{setUpdatingId(asset.id);try{const updated=asset.active?await mediaApi.removeAsset(asset.id):await mediaApi.activateAsset(asset.id);setAssets(old=>old.map(item=>item.id===updated.id?updated:item));if(['PRODUCT_IMAGE','PRODUCT_VIDEO'].includes(asset.assetType))await refreshBundle()}catch(e){setError(e instanceof Error?e.message:'Não foi possível atualizar a mídia.')}finally{setUpdatingId(null)}};
  const deleteAsset=async(id:string)=>{try{await mediaApi.deleteAsset(id);setAssets(old=>old.filter(asset=>asset.id!==id));await refreshBundle();setRemovingId(null)}catch(e){setError(e instanceof Error?e.message:'Não foi possível remover a mídia.')}};
  const classificationFor=(asset:MediaAsset)=>({HERO_IMAGE:'Principal',ALTERNATE_IMAGE:'Alternativa',DETAIL_IMAGE:'Detalhe',ACCESSORY_IMAGE:'Acessório',PACKAGE_IMAGE:'Embalagem',CONTEXT_IMAGE:'Contexto',FEATURE_IMAGE:'Recurso',UNKNOWN_PRODUCT_MEDIA:'Imagem do produto'}[asset.metadata?.classification??'UNKNOWN_PRODUCT_MEDIA']??'Imagem do produto');
  const sourceFor=(asset:MediaAsset)=>isMarketplaceImage(asset)?'Mercado Livre':'Manual/Outra origem';
  const renderProductImage=(asset:MediaAsset)=><article className="product-media-card" key={asset.id}>
    {asset.active?<img src={mediaApi.assetUrl(asset.id)} loading="lazy" alt={`${classificationFor(asset)}: ${asset.logicalName}`}/>:<div className="asset-placeholder product-media-placeholder">Imagem inativa</div>}
    <div className="product-media-card-copy"><b>{asset.logicalName}</b><span className="product-media-classification">{classificationFor(asset)}</span><span>{asset.width&&asset.height?`${asset.width} × ${asset.height}`:'Dimensões indisponíveis'}</span><span className={isMarketplaceImage(asset)?'product-media-origin official':'product-media-origin'}>{sourceFor(asset)}</span><strong className={asset.active?'asset-status active':'asset-status'}>{asset.active?'Ativo':'Inativo'}</strong></div>
    <div className="asset-card-actions"><button type="button" className="ghost-button small" disabled={updatingId===asset.id} onClick={()=>void toggle(asset)}>{updatingId===asset.id?'Atualizando…':asset.active?'Desativar':'Ativar'}</button><button type="button" className="danger-button small" onClick={()=>setRemovingId(asset.id)}>Remover</button></div>
    <details className="product-media-technical"><summary>Detalhes técnicos</summary><code>{asset.id}</code><small>Origem: {asset.metadata?.sourceKind??'Envio local'}{asset.metadata?.sourceEvidenceType?` · ${asset.metadata.sourceEvidenceType}`:''}</small></details>
    {removingId===asset.id&&<div className="asset-remove-confirm" role="alertdialog" aria-label="Confirmar remoção"><p>Remover esta mídia permanentemente?</p><button type="button" className="ghost-button small" onClick={()=>setRemovingId(null)}>Cancelar</button><button type="button" className="danger-button small" onClick={()=>void deleteAsset(asset.id)}>Remover</button></div>}
  </article>;
  const libraryAssets=assets.filter(asset=>asset.assetType!=='PRODUCT_IMAGE');
  return <>
    <section className="panel media-assets product-media-workspace" aria-labelledby="product-media-title">
      <div className="panel-head"><h2 id="product-media-title">Fontes visuais do produto</h2><button type="button" className="primary-button" disabled={syncing||loading} onClick={()=>void sync()}>{syncing?'Sincronizando…':'Sincronizar fotos do Mercado Livre'}</button></div>
      {syncResult&&<div className={`media-sync-summary${syncResult.failedCount||syncResult.status==='UNAVAILABLE'&&syncResult.reasonCode==='PRODUCT_MEDIA_SOURCE_NOT_FOUND'?' partial':''}`} role="status"><b>{syncResult.status==='UNAVAILABLE'&&syncResult.reasonCode==='PRODUCT_MEDIA_SOURCE_NOT_FOUND'?'Não encontramos fotos oficiais para este produto. Atualize os dados do Mercado Livre e tente novamente.':syncResult.failedCount?`${activeImages.length} de ${syncResult.sourcePictureCount} ${syncResult.sourcePictureCount===1?'imagem disponível':'imagens disponíveis'}; ${syncResult.failedCount} não puderam ser importadas.`:syncResult.downloadedCount===0&&syncResult.reusedCount>0?`Nenhuma nova imagem. ${syncResult.reusedCount} ${syncResult.reusedCount===1?'imagem já estava':'imagens já estavam'} atualizadas.`:`${activeImages.length} ${activeImages.length===1?'imagem disponível':'imagens disponíveis'}. ${syncResult.downloadedCount} ${syncResult.downloadedCount===1?'nova':'novas'} · ${syncResult.reusedCount} já existentes · ${syncResult.failedCount} ${syncResult.failedCount===1?'falha':'falhas'}.`}</b>
        {syncResult.failedCount>0&&<details><summary>Ver detalhes das falhas</summary><ul>{(syncResult.failures??[]).map((failure,index)=><li key={`${failure.remotePictureId}-${index}`}>{friendlyMediaError(failure.code)}</li>)}</ul></details>}
      </div>}
      {error&&<p className="inline-error" role="alert">{error}</p>}
      {loading?<p className="empty" role="status">Carregando as fontes visuais…</p>:<>
        <div className="product-media-overview" aria-live="polite"><div className="product-media-metric"><span>Imagens disponíveis</span><b>{usableImages.length}</b></div><div className="product-media-metric"><span>Grupos visuais</span><b>{uniqueVisualGroups}</b></div><div className="product-media-metric"><span>Diversidade</span><b>{bundle?diversityLabels[bundle.diversityLevel]:'Não avaliada'}</b></div><div className="product-media-metric"><span>Qualidade visual</span><b>{bundle?.qualityCheck==='PASS'?'Aprovada':usableImages.length?'Limitada':'Sem imagens'}</b></div><div className="product-media-readiness"><span>Prontidão</span><Badge tone={usableImages.length===0?'warning':uniqueVisualGroups>=3?'success':'warning'}>{usableImages.length===0?'Sem imagens':uniqueVisualGroups>=3?'Pronto':'Limitado'}</Badge></div></div>
        {usableImages.length>0&&uniqueVisualGroups<3&&<p className="media-notice">Material visual limitado — o vídeo poderá repetir imagens. Uma imagem válida ainda permite preparar a produção.</p>}
        {usableImages.length>0&&uniqueVisualGroups<3&&<p className="media-notice">Material visual limitado — o vídeo poderá repetir imagens. Uma imagem válida ainda permite preparar a produção.</p>}
        {activeImages.length?<div className="product-media-gallery" role="region" aria-label="Galeria de imagens do produto">{activeImages.map(renderProductImage)}</div>:<div className="product-media-empty" role="status"><b>Nenhuma imagem ativa disponível para este produto.</b><p>{productMedia?.status==='UNAVAILABLE'?'Não encontramos fotos oficiais do produto. Atualize os dados do Mercado Livre na Curadoria e tente sincronizar novamente.':'Sincronize as fotos oficiais ou adicione uma imagem local pela biblioteca de mídia.'}</p></div>}
        {inactiveImages.length>0&&<details className="product-media-inactive"><summary>Imagens inativas ({inactiveImages.length})</summary><div className="product-media-gallery">{inactiveImages.map(renderProductImage)}</div></details>}
        <details className="product-media-bundle-details"><summary>Resumo de diversidade</summary>{bundle?<p>{bundle.assetCount} arquivos · {bundle.uniqueVisualGroups} grupos visuais · {bundle.videoCount} vídeos · {bundle.detailCount} detalhes · {bundle.heroCount} imagens principais</p>:<p>Não foi possível avaliar a diversidade visual neste momento.</p>}</details>
      </>}
    </section>
    <section className="panel media-assets media-library"><div className="panel-head"><h2>Biblioteca de mídia</h2></div>
      {error&&<p className="inline-error" role="alert">{error}</p>}
      <form onSubmit={upload}>
        <label>Tipo<select name="assetType" value={assetType} onChange={event=>{const value=event.target.value;setAssetType(value);setClassification(value==='PRODUCT_VIDEO'?'VIDEO_CLIP':'UNKNOWN_PRODUCT_MEDIA')}}><option value="PRODUCT_IMAGE">Imagem do produto</option><option value="PRODUCT_VIDEO">Vídeo do produto</option><option value="AVATAR_IMAGE">Avatar</option><option value="LOGO">Marca</option></select></label>
        {(assetType==='PRODUCT_IMAGE'||assetType==='PRODUCT_VIDEO')&&<label>Classificação<select name="classification" value={classification} onChange={event=>setClassification(event.target.value)}>{classificationOptions.filter(([value])=>assetType==='PRODUCT_VIDEO'?value==='VIDEO_CLIP':value!=='VIDEO_CLIP').map(([value,text])=><option key={value} value={value}>{text}</option>)}</select></label>}
        {assetType==='AVATAR_IMAGE'&&<><label>Personagem<select name="character" value={character} onChange={event=>setCharacter(event.target.value)}><option value="BRUNO">Bruno</option><option value="CAROL">Carol</option></select></label><label>Expressão<select name="avatarState">{avatarStates[character].map(([value,text])=><option key={value} value={value}>{text}</option>)}</select></label></>}
        <label>Arquivo<input name="file" type="file" accept={assetType==='PRODUCT_VIDEO'?'video/mp4,video/quicktime,video/webm':'image/png,image/jpeg,image/webp'} required/></label><button type="submit" className="ghost-button">Enviar mídia</button>
      </form>
      <div className="asset-grid">{libraryAssets.map(asset=>{const analyzed=bundle?.assets.find(item=>item.assetId===asset.id),isVideo=asset.assetType==='PRODUCT_VIDEO';return <article className="asset-card" key={asset.id}>{asset.active?(isVideo?<video muted preload="metadata" src={mediaApi.assetUrl(asset.id)}/>:<img src={mediaApi.assetUrl(asset.id)} alt={`Prévia: ${asset.logicalName}`} loading="lazy"/>):<span className="asset-placeholder">Mídia inativa</span>}<div><b>{asset.logicalName}</b><small>{assetLabels[asset.assetType]??'Mídia'}{asset.metadata?.speaker?` · ${asset.metadata.speaker==='BRUNO'?'Bruno':'Carol'} · ${avatarStates[asset.metadata.speaker]?.find(([value])=>value===asset.metadata?.state)?.[1]??'Neutro'}`:''}</small>{analyzed&&<small>{analyzed.width&&analyzed.height?`${analyzed.width} × ${analyzed.height} · `:''}{classificationLabels[analyzed.classification]} · Grupo {analyzed.duplicateGroup} · {analyzed.warnings.length?'Não utilizável':'Utilizável'}</small>}<strong className={asset.active?'asset-status active':'asset-status'}>{asset.active?'Ativo':'Inativo'}</strong></div><div className="asset-card-actions"><button type="button" className="ghost-button small" disabled={updatingId===asset.id} onClick={()=>void toggle(asset)}>{updatingId===asset.id?'Atualizando…':asset.active?'Desativar':'Ativar'}</button><button type="button" className="danger-button small" onClick={()=>setRemovingId(asset.id)}>Remover</button></div>{removingId===asset.id&&<div className="asset-remove-confirm" role="alertdialog" aria-label="Confirmar remoção"><p>Remover esta mídia permanentemente?</p><button type="button" className="ghost-button small" onClick={()=>setRemovingId(null)}>Cancelar</button><button type="button" className="danger-button small" onClick={()=>void deleteAsset(asset.id)}>Remover</button></div>}</article>})}</div>
      {libraryAssets.length===0&&!loading&&<p className="empty">Nenhum outro arquivo de mídia está cadastrado.</p>}
    </section>
  </>;
}
