import{useCallback,useEffect,useState}from'react';
import{mediaApi}from'../api/media';
import type{MediaAsset,PublicationReadiness}from'../types';
import'./PublicationReadiness.css';

const statusLabel:Record<string,string>={READY:'Pronto',READY_WITH_WARNINGS:'Pronto com pendências',BLOCKED:'Bloqueado',UNKNOWN:'Desconhecido',AUDIO_PRESENT:'Pronto',AUDIO_PLATFORM_SELECTION_REQUIRED:'Seleção na plataforma pendente',AUDIO_MISSING:'Pendente',AUDIO_INVALID:'Inválido',PRESENT:'Pronto',MISSING:'Pendente',NOT_APPLICABLE:'Não aplicável'};
export function PublicationReadinessPanel({creativeId}:{creativeId:string}){
 const[data,setData]=useState<PublicationReadiness|null>(null),[audioAssets,setAudioAssets]=useState<MediaAsset[]>([]),[audioMode,setAudioMode]=useState<'NONE'|'LOCAL'|'PLATFORM'>('NONE'),[audioId,setAudioId]=useState(''),[text,setText]=useState(''),[placement,setPlacement]=useState('CAPTION'),[busy,setBusy]=useState(false),[message,setMessage]=useState(''),[error,setError]=useState('');
 const load=useCallback(async()=>{try{const[result,assets]=await Promise.all([mediaApi.publicationReadiness(creativeId),mediaApi.audioAssets(creativeId)]);setData(result);setAudioAssets(assets.filter(x=>x.assetType.startsWith('AUDIO_')))}catch(e){setError(e instanceof Error?e.message:'Não foi possível avaliar a prontidão.')}},[creativeId]);useEffect(()=>{void load()},[load]);
 const prepare=async()=>{setBusy(true);setError('');setMessage('');try{const audioPlan=audioMode==='PLATFORM'?{mode:'PLATFORM',sourceType:'TIKTOK_CML',selectionRequiredAtPublication:true}:audioMode==='LOCAL'?{mode:'LOCAL',mediaAssetId:audioId}:{mode:'NONE'};const result=await mediaApi.preparePublicationPackage(creativeId,{distributionMode:'PAID_AD',format:'CAROUSEL',audioPlan,disclosurePlan:{affiliateRelationship:'AFFILIATE_LINK',requirementStatus:'UNKNOWN',status:text?'PRESENT':'MISSING',text:text||null,placement,platformToolRequired:false},trackingPlan:{}});setData(result);setMessage('Pacote de publicação preparado. Nenhuma publicação foi realizada.')}catch(e){setError(e instanceof Error?e.message:'Não foi possível preparar o pacote.')}finally{setBusy(false)}};
 if(!data)return <section className="panel"><h2>Prontidão para publicação</h2>{error?<p role="alert" className="inline-error">{error}</p>:<p className="muted">Avaliando…</p>}</section>;
 return <section className="panel publication-readiness"><div className="panel-head"><div><h2>Prontidão para publicação</h2><p className="muted">Checklist para publicação manual. Esta área não publica nem conecta contas.</p></div><strong className={'readiness-status '+data.readinessStatus.toLowerCase()}>{statusLabel[data.readinessStatus]??data.readinessStatus}</strong></div>{error&&<p role="alert" className="inline-error">{error}</p>}{message&&<p role="status" className="media-notice">{message}</p>}<div className="readiness-grid"><span>Criativo<b>{data.approvalStatus==='APPROVED'?'Aprovado':'Não aprovado'}</b></span><span>Assets<b>{data.assetFiles.length?'Prontos':'Pendentes'}</b></span><span>Variante do canal<b>{data.channelVariantFingerprint?'Pronta':'Pendente'}</b></span><span>Áudio<b>{statusLabel[data.audioPlan.status]??data.audioPlan.status}</b></span><span>Disclosure<b>{data.disclosurePlan.requirementStatus==='UNKNOWN'?'Revisão necessária':statusLabel[data.disclosurePlan.status]??data.disclosurePlan.status}</b></span><span>URL<b>{data.destinationUrl?'Pronta':'Pendente'}</b></span></div><fieldset><legend>Áudio</legend><label><input type="checkbox" checked={audioMode==='LOCAL'} onChange={e=>setAudioMode(e.target.checked?'LOCAL':'NONE')}/> Usar arquivo de áudio local</label>{audioMode==='LOCAL'&&<label>Arquivo<select aria-label="Arquivo de áudio" value={audioId} onChange={e=>setAudioId(e.target.value)}><option value="">Selecione</option>{audioAssets.map(x=><option key={x.id} value={x.id}>{x.logicalName}</option>)}</select></label>}<label><input type="checkbox" checked={audioMode==='PLATFORM'} onChange={e=>setAudioMode(e.target.checked?'PLATFORM':'NONE')}/> Selecionar música na TikTok Commercial Music Library ao publicar</label><small>Nenhuma música será baixada ou selecionada agora.</small></fieldset><fieldset><legend>Disclosure</legend><label>Relacionamento<input value="Link de afiliado" readOnly/></label><label>Exigência<input value="Desconhecida — revisão manual necessária" readOnly/></label><label>Texto configurado<textarea value={text} onChange={e=>setText(e.target.value)} placeholder="Ex.: Este conteúdo contém link de afiliado."/></label><label>Posicionamento<select value={placement} onChange={e=>setPlacement(e.target.value)}><option value="CAPTION">Legenda</option><option value="CREATIVE">Criativo</option><option value="PLATFORM_LABEL">Identificação da plataforma</option><option value="MULTIPLE">Múltiplos</option></select></label></fieldset>{data.blockers.length>0&&<div><h3>Pendências bloqueantes</h3><ul>{data.blockers.map(x=><li key={x.code}>{x.message}</li>)}</ul></div>}{data.warnings.length>0&&<div><h3>Ações manuais</h3><ul>{data.warnings.map(x=><li key={x.code}>{x.message}</li>)}</ul></div>}<button type="button" className="primary-button" disabled={busy||(audioMode==='LOCAL'&&!audioId)} onClick={prepare}>{busy?'Preparando…':'Preparar pacote de publicação'}</button></section>;
}
