import{useEffect,useState}from'react';
import{mediaApi}from'../api/media';
import type{StaticCreativePlan}from'../types';

const layouts:Record<string,string>={PRODUCT_CENTER:'Produto central',PRODUCT_LEFT_FEATURES_RIGHT:'Produto à esquerda',PRODUCT_RIGHT_FEATURES_LEFT:'Produto à direita',PRODUCT_TOP_FEATURES_BOTTOM:'Produto acima',FEATURE_STRIP:'Faixa de atributos',MINIMAL_HERO:'Produto em destaque'};
const checkLabels:Record<string,string>={STATIC_PRODUCT_PROMINENCE:'Produto em destaque',STATIC_TEXT_OVERFLOW:'Texto dentro da área segura',STATIC_FEATURE_COUNT:'Quantidade de informações',STATIC_FEATURE_PROVENANCE:'Origem das informações',STATIC_CONTRAST:'Contraste',STATIC_CTA_CLARITY:'CTA claro',STATIC_MEDIA_QUALITY:'Qualidade da mídia',CAROUSEL_CARD_COUNT:'Quantidade de cards',CAROUSEL_MEDIA_DIVERSITY:'Diversidade de mídia',CAROUSEL_REPETITION:'Repetição',CAROUSEL_STORY_FLOW:'Progressão',CAROUSEL_CTA_PRESENT:'CTA presente',CAROUSEL_FEATURE_PROVENANCE:'Origem das informações'};

export function StaticProduction({creativeId}:{creativeId:string}){
 const[format,setFormat]=useState<'VIDEO_SHORT'|'STATIC_CARD'|'CAROUSEL'>('VIDEO_SHORT'),[plan,setPlan]=useState<StaticCreativePlan|null>(null),[result,setResult]=useState<StaticCreativePlan|null>(null),[busy,setBusy]=useState(false),[error,setError]=useState('');
 useEffect(()=>{if(format==='VIDEO_SHORT'){setPlan(null);setResult(null);return}mediaApi.staticPlan(creativeId,format).then(setPlan).catch(e=>setError(e instanceof Error?e.message:'Não foi possível preparar o formato.'))},[creativeId,format]);
 if(format==='VIDEO_SHORT')return <section className="panel static-format"><label>Formato<select aria-label="Formato" value={format} onChange={e=>setFormat(e.target.value as typeof format)}><option value="VIDEO_SHORT">Vídeo curto</option><option value="STATIC_CARD">Card estático</option><option value="CAROUSEL">Carrossel</option></select></label></section>;
 return <section className="panel static-format"><div className="panel-head"><h2>{format==='STATIC_CARD'?'Card estático':'Carrossel'}</h2><label>Formato<select aria-label="Formato" value={format} onChange={e=>setFormat(e.target.value as typeof format)}><option value="VIDEO_SHORT">Vídeo curto</option><option value="STATIC_CARD">Card estático</option><option value="CAROUSEL">Carrossel</option></select></label></div>{error&&<p role="alert" className="inline-error">{error}</p>}{plan&&<div className="static-plan"><div><small>Layout</small><b>{layouts[plan.layout]??plan.layout}</b></div><div><small>Headline</small><b>{plan.headline.text}</b></div><div><small>CTA</small><b>{plan.cta.text}</b></div><div className="static-features"><small>Informações verificadas</small>{plan.features.length?plan.features.map(x=><label key={x.sourceReference}><input type="checkbox" checked readOnly/>{x.displayLabel}: {x.displayValue}<em>{x.verified?'Verificada':'Não verificada'}</em></label>):<p>Nenhum atributo verificável disponível.</p>}</div><button type="button" className="primary-button" disabled={busy} onClick={async()=>{setBusy(true);setError('');try{setResult(await mediaApi.staticPreview(creativeId,format))}catch(e){setError(e instanceof Error?e.message:'Não foi possível gerar o preview.')}finally{setBusy(false)}}}>{busy?'Gerando…':format==='STATIC_CARD'?'Gerar card':'Gerar carrossel'}</button></div>}{result?.files&&<><div className={format==='CAROUSEL'?'static-preview carousel':'static-preview'}>{result.files.map(file=><img key={file} src={mediaApi.staticContentUrl(creativeId,format,file.split('/').pop()!)} alt={format==='STATIC_CARD'?'Preview do card':'Card do carrossel'}/>)}</div><div className="static-checks">{Object.entries(result.qualityChecks).map(([key,value])=><span key={key} className={value==='PASS'?'pass':'warning'}>{checkLabels[key]??key}: {value==='PASS'?'Aprovado':'Atenção'}</span>)}</div></>}</section>;
}
