import{fireEvent,render,screen,waitFor}from'@testing-library/react';
import{afterEach,describe,expect,it,vi}from'vitest';
import{campaignsApi}from'../api/campaigns';
import{AffiliateDestination}from'../components/AffiliateDestination';
import type{AffiliateDestination as Destination}from'../types';

const base:Destination={candidateId:'c1',productTitle:'Parafusadeira doméstica',sourcePermalink:'https://produto.mercadolivre.com.br/MLB-123456789-produto',expectedItemId:'MLB123456789',affiliateUrl:null,affiliateUrlSource:null,affiliateValidationStatus:'UNKNOWN',affiliateItemId:null,destinationUrl:null,destinationStrategy:'UNKNOWN',failureCode:null};

describe('Destino comercial afiliado',()=>{afterEach(()=>vi.restoreAllMocks());it('orienta o operador e valida o link sem prometer comissão',async()=>{vi.spyOn(campaignsApi,'affiliateDestination').mockResolvedValue(base);const configure=vi.spyOn(campaignsApi,'configureAffiliateDestination').mockResolvedValue({...base,affiliateUrl:'https://meli.la/abc',affiliateUrlSource:'MANUAL_OFFICIAL_TOOL',affiliateValidationStatus:'VALID',affiliateItemId:'MLB123456789',destinationUrl:'https://meli.la/abc',destinationStrategy:'DIRECT_AFFILIATE_LINK'});render(<AffiliateDestination candidateId="c1"/>);expect(await screen.findByText(/Abra o Gerador de Links/)).toBeInTheDocument();fireEvent.change(screen.getByPlaceholderText('Cole o link gerado oficialmente'),{target:{value:'https://meli.la/abc'}});fireEvent.click(screen.getByRole('button',{name:'Validar link'}));await waitFor(()=>expect(configure).toHaveBeenCalledWith('c1','https://meli.la/abc'));expect(await screen.findByText(/Link de afiliado válido para atribuição elegível/)).toBeInTheDocument();expect(screen.queryByText(/Você receberá comissão/i)).not.toBeInTheDocument()});

it('mostra item divergente e estado não verificável',async()=>{vi.spyOn(campaignsApi,'affiliateDestination').mockResolvedValue({...base,affiliateValidationStatus:'INVALID',failureCode:'AFFILIATE_ITEM_MISMATCH'});const{rerender}=render(<AffiliateDestination candidateId="c1"/>);expect(await screen.findByText('O link aponta para outro produto.')).toBeInTheDocument();vi.mocked(campaignsApi.affiliateDestination).mockResolvedValue({...base,affiliateValidationStatus:'UNVERIFIED'});rerender(<AffiliateDestination candidateId="c2"/>);expect(await screen.findByText('Não foi possível verificar o produto deste link.')).toBeInTheDocument()});});
