import{fireEvent,render,screen,waitFor}from'@testing-library/react';
import{MemoryRouter,Route,Routes}from'react-router-dom';
import{afterEach,describe,expect,it,vi}from'vitest';
import{CreativePage}from'../pages/Creatives';

const response=(body:unknown)=>Promise.resolve(new Response(JSON.stringify(body),{status:200,headers:{'Content-Type':'application/json'}}));
const scene={id:'s1',creativeId:'cr1',orderIndex:0,sceneType:'AVATAR',speaker:'BRUNO',purpose:'HOOK',narrationText:'Hook',onScreenText:null,visualInstruction:null,avatarState:'WARNING',durationSeconds:4,requiredWarningCodes:[]};
function setup(){let status='DRAFT';const approval={id:'approval1',type:'CREATIVE',status:'PENDING',title:'Aprovar',description:'Revisão',entityType:'CREATIVE',entityId:'cr1',requestedPayload:{},decidedAt:null,decisionReason:null,createdAt:'2026-09-23T10:00:00Z',updatedAt:'2026-09-23T10:00:00Z'};const fetchMock=vi.fn(async(input:string|URL,init?:RequestInit)=>{const url=String(input),method=init?.method??'GET';if(url.endsWith('/creatives/cr1/submit-for-review')&&method==='POST'){status='READY_FOR_REVIEW';return response(approval)}if(url.endsWith('/approvals/approval1/approve')&&method==='POST'){status='APPROVED';return response({...approval,status:'APPROVED'})}if(url.includes('/approvals?status=PENDING'))return response(status==='READY_FOR_REVIEW'?[approval]:[]);if(url.endsWith('/creatives/cr1/scenes'))return response([scene]);if(url.endsWith('/creatives/cr1/readiness'))return response({state:status==='APPROVED'?'APPROVED':'READY_FOR_REVIEW',checks:{hook:true},sceneCount:1,compliance:{status:'PASS',reasons:[],requiredWarningCoverage:[]}});if(url.endsWith('/creatives/cr1'))return response({id:'cr1',campaignId:'cp1',experimentId:null,name:'Cópia',status,contentType:'SHORT_VIDEO',targetChannel:'GENERIC',angleTypeSnapshot:null,objectiveSnapshot:'EDUCATION',editorialVerdictSnapshot:'WORTH_IT',priceVerdictSnapshot:'FAIR_PRICE',title:'Título',contentPremise:'Premissa',hook:'Hook',bodyScript:'Roteiro',cta:'Compare',estimatedDurationSeconds:20,disclosureText:'Afiliado',requiredWarnings:[],forbiddenClaims:[],generationMode:'MANUAL',variantGroup:null,parentCreativeId:'source',variantLabel:null});if(url.endsWith('/campaigns/cp1'))return response({id:'cp1',name:'Produto',status:'APPROVED'});return response({})});vi.stubGlobal('fetch',fetchMock);render(<MemoryRouter initialEntries={['/criativos/cr1']}><Routes><Route path="/criativos/:id" element={<CreativePage/>}/></Routes></MemoryRouter>);return fetchMock}
afterEach(()=>vi.unstubAllGlobals());
describe('aprovação do Creative na tela de detalhe',()=>{
 it('envia DRAFT para revisão, aprova e torna o Creative somente leitura',async()=>{const fetchMock=setup();const submit=await screen.findByRole('button',{name:'Enviar para revisão'});fireEvent.click(submit);expect(await screen.findByText('Creative enviado para revisão.')).toBeInTheDocument();await waitFor(()=>expect(screen.getAllByText('Pronto para revisão').length).toBeGreaterThan(0));const approve=await screen.findByRole('button',{name:'Aprovar'});await waitFor(()=>expect(approve).toBeEnabled());expect(screen.getByRole('button',{name:'Rejeitar'})).toBeInTheDocument();fireEvent.click(approve);expect(await screen.findByText('Creative aprovado.')).toBeInTheDocument();await waitFor(()=>expect(screen.getAllByText('Aprovado').length).toBeGreaterThan(0));expect(screen.queryByRole('button',{name:'Salvar criativo'})).not.toBeInTheDocument();expect(screen.queryByRole('button',{name:'Editar'})).not.toBeInTheDocument();expect(screen.getByRole('button',{name:'Criar cópia editável'})).toBeInTheDocument();expect(fetchMock).toHaveBeenCalledWith(expect.stringContaining('/submit-for-review'),expect.objectContaining({method:'POST'}));expect(fetchMock).toHaveBeenCalledWith(expect.stringContaining('/approvals/approval1/approve'),expect.objectContaining({method:'POST'}));expect(fetchMock.mock.calls.filter(([input])=>String(input).endsWith('/creatives/cr1')).length).toBeGreaterThanOrEqual(3)});
});
