import{fireEvent,render,screen,waitFor}from'@testing-library/react';
import{MemoryRouter,Route,Routes}from'react-router-dom';
import{afterEach,describe,expect,it,vi}from'vitest';
import{CreativePage}from'../pages/Creatives';

const scene={id:'s1',creativeId:'cr1',orderIndex:0,sceneType:'PRODUCT',speaker:'NARRATOR',purpose:'BENEFIT',narrationText:'Cena para consulta',onScreenText:null,visualInstruction:null,avatarState:null,durationSeconds:4,requiredWarningCodes:[]};
const response=(body:unknown)=>Promise.resolve(new Response(JSON.stringify(body),{status:200,headers:{'Content-Type':'application/json'}}));
function setup(status:string){const creative={id:'cr1',campaignId:'cp1',experimentId:null,name:'Criativo',status,contentType:'SHORT_VIDEO',targetChannel:'GENERIC',angleTypeSnapshot:null,objectiveSnapshot:'EDUCATION',editorialVerdictSnapshot:'WORTH_IT',priceVerdictSnapshot:'FAIR_PRICE',title:'Título original',contentPremise:'Premissa',hook:'Hook original',bodyScript:'Roteiro',cta:'Compare',estimatedDurationSeconds:20,disclosureText:'Afiliado',requiredWarnings:[],forbiddenClaims:[],generationMode:'MANUAL',variantGroup:null,parentCreativeId:null,variantLabel:null};const copy={...creative,id:'copy1',name:'Criativo — cópia',status:'DRAFT',parentCreativeId:'cr1'};const fetchMock=vi.fn(async(input:string|URL,init?:RequestInit)=>{const url=String(input);if(url.endsWith('/creatives/cr1/duplicate')&&init?.method==='POST')return response(copy);if(url.endsWith('/scenes'))return response([{...scene,creativeId:url.includes('copy1')?'copy1':'cr1'}]);if(url.endsWith('/readiness'))return response({state:'NOT_READY',checks:{},sceneCount:1,compliance:{status:'PASS',reasons:[],requiredWarningCoverage:[]}});if(url.endsWith('/creatives/cr1'))return response(creative);if(url.endsWith('/creatives/copy1'))return response(copy);if(url.endsWith('/campaigns/cp1'))return response({id:'cp1',name:'Produto',status:'APPROVED'});return response({})});vi.stubGlobal('fetch',fetchMock);render(<MemoryRouter initialEntries={['/criativos/cr1']}><Routes><Route path="/criativos/:id" element={<CreativePage/>}/></Routes></MemoryRouter>);return fetchMock}
afterEach(()=>vi.unstubAllGlobals());

describe('modo somente leitura do Creative',()=>{
  it.each(['DRAFT','REJECTED'])('%s permanece editável',async status=>{setup(status);expect(await screen.findByLabelText('Título')).not.toHaveAttribute('readonly');expect(screen.getByLabelText('Canal')).toBeEnabled();expect(screen.getByRole('button',{name:'Salvar criativo'})).toBeInTheDocument();expect(screen.getByRole('button',{name:'Gerar estrutura inicial'})).toBeInTheDocument();expect(screen.getByRole('button',{name:'Adicionar cena'})).toBeInTheDocument();expect(screen.getByRole('button',{name:'Editar'})).toBeInTheDocument()});
  it.each([['READY_FOR_REVIEW','Criativo em revisão — aguarde a decisão para editar novamente.'],['APPROVED','Criativo aprovado — conteúdo bloqueado para edição.'],['ARCHIVED','Criativo arquivado — conteúdo somente para consulta.']])('%s fica somente leitura',async(status,message)=>{const fetchMock=setup(status);const title=await screen.findByDisplayValue('Título original');const hook=await screen.findByDisplayValue('Hook original');expect(title).toHaveAttribute('readonly');expect(hook).toHaveAttribute('readonly');expect(screen.getByLabelText('Canal')).toBeDisabled();expect(screen.getByLabelText('Duração')).toBeDisabled();expect(screen.getByText(message)).toBeInTheDocument();expect(screen.queryByText('Não salvo')).not.toBeInTheDocument();expect(screen.queryByRole('button',{name:'Salvar criativo'})).not.toBeInTheDocument();expect(screen.queryByRole('button',{name:'Gerar estrutura inicial'})).not.toBeInTheDocument();expect(screen.queryByRole('button',{name:'Adicionar cena'})).not.toBeInTheDocument();expect(screen.queryByRole('button',{name:'Editar'})).not.toBeInTheDocument();expect(screen.queryByRole('button',{name:'Excluir'})).not.toBeInTheDocument();fireEvent.change(hook,{target:{value:'alteração falsa'}});expect(hook).toHaveValue('Hook original');expect(fetchMock.mock.calls.some(([,init])=>['POST','PATCH','DELETE'].includes((init as RequestInit|undefined)?.method??''))).toBe(false)});
  it('duplica APPROVED, navega para a cópia editável e mostra confirmação',async()=>{const fetchMock=setup('APPROVED');fireEvent.click(await screen.findByRole('button',{name:'Criar cópia editável'}));await waitFor(()=>expect(fetchMock).toHaveBeenCalledWith(expect.stringContaining('/creatives/cr1/duplicate'),expect.objectContaining({method:'POST'})));expect(await screen.findByRole('status')).toHaveTextContent('Cópia criada. Você pode editar este Creative.');expect(await screen.findByText('Criativo — cópia')).toBeInTheDocument();expect(screen.getByRole('button',{name:'Salvar criativo'})).toBeInTheDocument();expect(screen.getByRole('button',{name:'Editar'})).toBeInTheDocument()});
});
