import{fireEvent,render,screen,waitFor}from'@testing-library/react';
import{afterEach,describe,expect,it,vi}from'vitest';
import{MediaProduction}from'../components/MediaProduction';

const diagnostic={ffmpeg:{status:'AVAILABLE'},ffprobe:{status:'AVAILABLE'},tts:{status:'NOT_CONFIGURED'},storage:{status:'AVAILABLE'}};
const completed={id:'job-1',creativeId:'cr1',renderType:'PREVIEW',status:'COMPLETED',actualDurationSeconds:27,outputSizeBytes:1048576,validationStatus:'VALID',validationDetails:{durationSeconds:29.9},progressPercent:100,currentStage:'COMPLETED',currentSceneIndex:4,totalScenes:5,errorCode:null,errorMessage:null,createdAt:'2026-09-21T12:00:00Z',completedAt:'2026-09-21T12:01:00Z'};
const response=(body:unknown,status=200)=>Promise.resolve(new Response(JSON.stringify(body),{status,headers:{'Content-Type':'application/json'}}));

afterEach(()=>vi.unstubAllGlobals());
describe('produção de mídia',()=>{
  it('diagnóstico crítico indisponível não cria MediaJob',async()=>{
    const unavailable={...diagnostic,ffmpeg:{status:'NOT_CONFIGURED'}};const fetchMock=vi.fn(async(input:string|URL)=>{const url=String(input);if(url.includes('/media-jobs?')||url.includes('/media-assets?'))return response([]);if(url.endsWith('/media/diagnostics'))return response(unavailable);return response({})});vi.stubGlobal('fetch',fetchMock);render(<MediaProduction creativeId="cr1" candidateId="candidate-1" requiresVoice/>);expect(await screen.findByText('Produção de mídia indisponível. Verifique a configuração local de vídeo e voz.')).toBeInTheDocument();expect(screen.getByRole('button',{name:'Gerar preview'})).toBeDisabled();expect(fetchMock.mock.calls.some(([input])=>String(input).includes('/from-creative/'))).toBe(false);
  });

  it('bloqueia duplo clique enquanto create e start estão em andamento',async()=>{
    let releaseCreate:(value:Response)=>void=()=>{};const pending=new Promise<Response>(resolve=>{releaseCreate=resolve});const queued={...completed,id:'job-double',status:'QUEUED',validationStatus:null,progressPercent:0,currentStage:null};const fetchMock=vi.fn(async(input:string|URL)=>{const url=String(input);if(url.includes('/media-jobs?')||url.includes('/media-assets?'))return response([]);if(url.endsWith('/media/diagnostics'))return response(diagnostic);if(url.endsWith('/media-jobs/from-creative/cr1'))return pending;if(url.endsWith('/media-jobs/job-double/start'))return response({...queued,status:'PREPARING',currentStage:'PREPARING'});return response({})});vi.stubGlobal('fetch',fetchMock);render(<MediaProduction creativeId="cr1" candidateId="candidate-1"/>);const button=await screen.findByRole('button',{name:'Gerar preview'});await waitFor(()=>expect(button).toBeEnabled());fireEvent.click(button);fireEvent.click(button);await waitFor(()=>expect(fetchMock.mock.calls.filter(([input])=>String(input).includes('/from-creative/'))).toHaveLength(1));releaseCreate(await response(queued,201));await waitFor(()=>expect(fetchMock).toHaveBeenCalledWith(expect.stringContaining('/job-double/start'),expect.anything()));
  });

  it('falha no start mantém QUEUED explicado e permite cancelar',async()=>{
    const queued={...completed,id:'orphan',status:'QUEUED',validationStatus:null,progressPercent:0,currentStage:null};const canceled={...queued,status:'CANCELED',currentStage:'CANCELED'};const fetchMock=vi.fn(async(input:string|URL,init?:RequestInit)=>{const url=String(input);if(url.includes('/media-jobs?')||url.includes('/media-assets?'))return response([]);if(url.endsWith('/media/diagnostics'))return response(diagnostic);if(url.endsWith('/media-jobs/from-creative/cr1'))return response(queued,201);if(url.endsWith('/media-jobs/orphan/start'))return response({detail:'Preflight indisponível'},409);if(url.endsWith('/media-jobs/orphan/cancel')&&init?.method==='POST')return response(canceled);return response({})});vi.stubGlobal('fetch',fetchMock);render(<MediaProduction creativeId="cr1" candidateId="candidate-1"/>);const button=await screen.findByRole('button',{name:'Gerar preview'});await waitFor(()=>expect(button).toBeEnabled());fireEvent.click(button);expect(await screen.findByText(/job foi criado, mas não pôde ser iniciado/i)).toBeInTheDocument();expect(screen.getByText(/ainda não foi iniciado/i)).toBeInTheDocument();fireEvent.click(screen.getByRole('button',{name:'Cancelar job'}));await waitFor(()=>expect(fetchMock).toHaveBeenCalledWith(expect.stringContaining('/media-jobs/orphan/cancel'),expect.objectContaining({method:'POST'})));expect(screen.getAllByText('Cancelado').length).toBeGreaterThan(0);
  });
  it('renderiza ações reais e permite ativar, desativar e remover',async()=>{
    const active={id:'asset-active',assetType:'PRODUCT_IMAGE',ownerType:'CANDIDATE',ownerId:'candidate-1',logicalName:'Produto ativo',relativePath:'assets/active.png',mimeType:'image/png',width:2,height:3,fileSizeBytes:32,metadata:{},active:true,createdAt:'2026-09-21T12:00:00Z',updatedAt:'2026-09-21T12:00:00Z'},inactive={...active,id:'asset-inactive',logicalName:'Produto inativo',relativePath:'assets/inactive.png',active:false};
    const fetchMock=vi.fn(async(input:string|URL,init?:RequestInit)=>{const url=String(input);if(url.includes('/media-jobs?'))return response([]);if(url.includes('/media-assets?')&&url.includes('active=true'))return response([active]);if(url.includes('/media-assets?')&&url.includes('active=false'))return response([inactive]);if(url.endsWith('/media/diagnostics'))return response(diagnostic);if(url.endsWith('/media-assets/asset-inactive/activate')&&init?.method==='POST')return response({...inactive,active:true});if(url.endsWith('/media-assets/asset-active')&&init?.method==='DELETE')return response({...active,active:false});if(url.endsWith('/media-assets/asset-inactive/permanent')&&init?.method==='DELETE')return new Response(null,{status:204});return response({})});vi.stubGlobal('fetch',fetchMock);render(<MediaProduction creativeId="cr1" candidateId="candidate-1"/>);
    const activeCard=(await screen.findByText('Produto ativo')).closest('article')!,inactiveCard=screen.getByText('Produto inativo').closest('article')!;expect(activeCard).toHaveTextContent('Ativo');expect(activeCard).toHaveTextContent('Desativar');expect(activeCard).toHaveTextContent('Remover');expect(activeCard).not.toHaveTextContent('Ativar');expect(inactiveCard).toHaveTextContent('Inativo');expect(inactiveCard).toHaveTextContent('Ativar');expect(inactiveCard).toHaveTextContent('Remover');expect(inactiveCard).not.toHaveTextContent('Desativar');
    fireEvent.click(screen.getByRole('button',{name:'Ativar'}));await waitFor(()=>expect(fetchMock).toHaveBeenCalledWith(expect.stringContaining('/media-assets/asset-inactive/activate'),expect.objectContaining({method:'POST'})));expect(screen.getByText('Produto inativo').closest('article')).toHaveTextContent('Ativo');
    fireEvent.click(activeCard.querySelector('button')!);await waitFor(()=>expect(fetchMock).toHaveBeenCalledWith(expect.stringMatching(/media-assets\/asset-active$/),expect.objectContaining({method:'DELETE'})));expect(screen.getByText('Produto ativo').closest('article')).toHaveTextContent('Inativo');
    fireEvent.click(screen.getByText('Produto inativo').closest('article')!.querySelector('.danger-button')!);expect(screen.getByRole('alertdialog')).toHaveTextContent('Remover esta imagem permanentemente?');fireEvent.click(screen.getByRole('alertdialog').querySelector('.danger-button')!);await waitFor(()=>expect(fetchMock).toHaveBeenCalledWith(expect.stringContaining('/media-assets/asset-inactive/permanent'),expect.objectContaining({method:'DELETE'})));expect(screen.queryByText('Produto inativo')).not.toBeInTheDocument();
  });
  it('mostra status amigável, duração validada, player, download e diagnóstico sem detalhes do provider',async()=>{
    vi.stubGlobal('fetch',vi.fn(async(input:string|URL)=>{const url=String(input);if(url.includes('/media-jobs?'))return response([completed]);if(url.includes('/media-assets?'))return response([]);if(url.endsWith('/media/diagnostics'))return response(diagnostic);return response({})}));
    render(<MediaProduction creativeId="cr1" candidateId="candidate-1"/>);
    expect((await screen.findAllByText('Concluído')).length).toBeGreaterThan(0);expect(screen.getByText('29.9 s')).toBeInTheDocument();expect(screen.getByText('Voz').parentElement).toHaveTextContent('Não configurada');expect(screen.queryByText(/Piper|codec|540x960/i)).not.toBeInTheDocument();expect(document.querySelector('video')?.getAttribute('src')).toContain('/media-jobs/job-1/content');expect(screen.getByRole('link',{name:'Baixar vídeo'})).toHaveAttribute('href',expect.stringContaining('download=true'));
  });

  it('cria e inicia preview somente após ação do operador',async()=>{
    const queued={...completed,id:'job-2',status:'QUEUED',validationStatus:null,progressPercent:0,currentStage:null};const started={...queued,status:'PREPARING',progressPercent:5,currentStage:'PREPARING'};
    const fetchMock=vi.fn(async(input:string|URL)=>{const url=String(input);if(url.includes('/media-jobs?'))return response([]);if(url.includes('/media-assets?'))return response([]);if(url.endsWith('/media/diagnostics'))return response(diagnostic);if(url.endsWith('/media-jobs/from-creative/cr1'))return response(queued,201);if(url.endsWith('/media-jobs/job-2/start'))return response(started);return response(started)});vi.stubGlobal('fetch',fetchMock);render(<MediaProduction creativeId="cr1" candidateId="candidate-1"/>);await screen.findByText('Nenhum vídeo produzido para este criativo.');expect(fetchMock).not.toHaveBeenCalledWith(expect.stringContaining('/from-creative/'),expect.anything());fireEvent.click(screen.getByRole('button',{name:'Gerar preview'}));await waitFor(()=>expect(fetchMock).toHaveBeenCalledWith(expect.stringContaining('/media-jobs/from-creative/cr1'),expect.objectContaining({body:JSON.stringify({renderType:'PREVIEW'})})));expect(fetchMock).toHaveBeenCalledWith(expect.stringContaining('/media-jobs/job-2/start'),expect.objectContaining({method:'POST'}));expect((await screen.findAllByText('Preparando')).length).toBeGreaterThan(0);
  });

  it('falha amigável permite tentar novamente criando um novo job',async()=>{
    const failed={...completed,id:'failed',status:'FAILED',validationStatus:null,errorMessage:'Não foi possível renderizar uma das cenas.',currentStage:'FAILED'};const fetchMock=vi.fn(async(input:string|URL)=>{const url=String(input);if(url.includes('/media-jobs?'))return response([failed]);if(url.includes('/media-assets?'))return response([]);if(url.endsWith('/media/diagnostics'))return response(diagnostic);if(url.endsWith('/media-jobs/from-creative/cr1'))return response({...failed,id:'new-job',status:'QUEUED'},201);if(url.endsWith('/media-jobs/new-job/start'))return response({...failed,id:'new-job',status:'PREPARING',currentStage:'PREPARING'});return response({})});vi.stubGlobal('fetch',fetchMock);render(<MediaProduction creativeId="cr1" candidateId="candidate-1"/>);expect(await screen.findByText('Não foi possível renderizar uma das cenas.')).toBeInTheDocument();fireEvent.click(screen.getByRole('button',{name:'Tentar novamente'}));await waitFor(()=>expect(fetchMock).toHaveBeenCalledWith(expect.stringContaining('/media-jobs/from-creative/cr1'),expect.objectContaining({method:'POST'})));expect(fetchMock).not.toHaveBeenCalledWith(expect.stringContaining('/media-jobs/failed/start'),expect.anything());
  });
});
