import{fireEvent,render,screen,waitFor}from'@testing-library/react';
import{afterEach,describe,expect,it,vi}from'vitest';
import{MemoryRouter}from'react-router-dom';
import{MediaProduction}from'../components/MediaProduction';

const diagnostic={ffmpeg:{status:'AVAILABLE'},ffprobe:{status:'AVAILABLE'},tts:{status:'NOT_CONFIGURED'},storage:{status:'AVAILABLE'}};
const completed={id:'job-1',creativeId:'cr1',renderType:'PREVIEW',status:'COMPLETED',actualDurationSeconds:27,outputSizeBytes:1048576,validationStatus:'VALID',validationDetails:{durationSeconds:29.9},progressPercent:100,currentStage:'COMPLETED',currentSceneIndex:4,totalScenes:5,errorCode:null,errorMessage:null,createdAt:'2026-09-21T12:00:00Z',completedAt:'2026-09-21T12:01:00Z'};
const response=(body:unknown,status=200)=>Promise.resolve(new Response(JSON.stringify(body),{status,headers:{'Content-Type':'application/json'}}));
const handoff=(state='READY_TO_CREATE',job?:Record<string,unknown>)=>({state,creativeId:'cr1',creativeStatus:'APPROVED',renderType:'PREVIEW',creativeApprovalId:'approval-1',inputFingerprint:'fingerprint',mediaJobId:job?.id??null,mediaJobStatus:job?.status??null,attemptNumber:job?.attemptNumber??1,previousMediaJobId:null,reasonCode:null,blockers:[],warnings:[]});
type FetchMock=(input:string|URL,init?:RequestInit)=>Promise<Response>;
function controlledFetch(fetchMock:FetchMock,initialJobs:Record<string,unknown>[]=[]){let state=handoff(),activeJob:Record<string,unknown>|null=null;return vi.fn<FetchMock>(async(input,init)=>{const url=String(input),method=init?.method??'GET';if(url.includes('/media-handoff')){const renderType=url.includes('STANDARD')?'STANDARD':'PREVIEW';return response({...state,renderType})}if(url.includes('/media-jobs?')){const original=await fetchMock(input,init);const body=await original.clone().json().catch(()=>initialJobs);const listed=Array.isArray(body)?body:initialJobs;return response([...(activeJob?[activeJob]:[]),...listed.filter((job:Record<string,unknown>)=>job.id!==activeJob?.id)])}const result=await fetchMock(input,init);if(url.includes('/media-jobs/from-creative/')&&method==='POST'&&result.ok){activeJob=await result.clone().json();state=handoff('JOB_EXISTS',activeJob??undefined)}else if(/\/media-jobs\/[^/]+\/start$/.test(url)&&method==='POST'&&result.ok){activeJob=await result.clone().json();state=handoff('JOB_EXISTS',activeJob??undefined)}else if(/\/media-jobs\/[^/]+\/cancel$/.test(url)&&method==='POST'&&result.ok){activeJob=await result.clone().json();state=handoff('READY_TO_CREATE')}return result})}

afterEach(()=>vi.unstubAllGlobals());
describe('produção de mídia',()=>{
  it('diagnóstico crítico indisponível não cria MediaJob',async()=>{
    const unavailable={...diagnostic,ffmpeg:{status:'NOT_CONFIGURED'}};const queued={...completed,id:'diag-job',status:'QUEUED',validationStatus:null,progressPercent:0,currentStage:null};const fetchMock=vi.fn(async(input:string|URL)=>{const url=String(input);if(url.includes('/media-jobs?')||url.includes('/media-assets?'))return response([]);if(url.endsWith('/media/diagnostics'))return response(unavailable);if(url.endsWith('/media-jobs/from-creative/cr1'))return response(queued,201);return response({})});vi.stubGlobal('fetch',controlledFetch(fetchMock));render(<MediaProduction creativeId="cr1" candidateId="candidate-1" requiresVoice/>);const prepare=await screen.findByRole('button',{name:'Preparar preview'});expect(prepare).toBeEnabled();expect(screen.getByText('Diagnóstico técnico')).toBeInTheDocument();expect(fetchMock.mock.calls.some(([input])=>String(input).includes('/from-creative/'))).toBe(false);fireEvent.click(prepare);await screen.findByText('Produção preparada');expect(fetchMock).toHaveBeenCalledWith(expect.stringContaining('/media-jobs/from-creative/cr1'),expect.objectContaining({body:JSON.stringify({renderType:'PREVIEW'})}));expect(fetchMock.mock.calls.some(([input])=>String(input).includes('/start'))).toBe(false);
  });

  it('bloqueia duplo clique enquanto preparar e iniciar estão em andamento',async()=>{
    let releaseCreate:(value:Response)=>void=()=>{};const pending=new Promise<Response>(resolve=>{releaseCreate=resolve});const queued={...completed,id:'job-double',status:'QUEUED',validationStatus:null,progressPercent:0,currentStage:null};const started={...queued,status:'PREPARING',currentStage:'PREPARING'};const fetchMock=vi.fn<FetchMock>(async input=>{const url=String(input);if(url.includes('/media-jobs?')||url.includes('/media-assets?'))return response([]);if(url.endsWith('/media/diagnostics'))return response(diagnostic);if(url.endsWith('/media-jobs/from-creative/cr1'))return pending;if(url.endsWith('/media-jobs/job-double/start'))return response(started);return response({})});vi.stubGlobal('fetch',controlledFetch(fetchMock));render(<MediaProduction creativeId="cr1" candidateId="candidate-1"/>);const button=await screen.findByRole('button',{name:'Preparar preview'});fireEvent.click(button);fireEvent.click(button);await waitFor(()=>expect(fetchMock.mock.calls.filter(([input])=>String(input).includes('/from-creative/'))).toHaveLength(1));releaseCreate(await response(queued,201));expect(await screen.findByText('Produção preparada')).toBeInTheDocument();expect(fetchMock.mock.calls.some(([input])=>String(input).includes('/start'))).toBe(false);const startButton=screen.getByRole('button',{name:'Iniciar renderização'});await waitFor(()=>expect(startButton).toBeEnabled());fireEvent.click(startButton);expect(await screen.findByRole('group',{name:'Confirmar início da renderização'})).toBeInTheDocument();const confirm=screen.getByRole('button',{name:'Confirmar início'});fireEvent.click(confirm);fireEvent.click(confirm);await waitFor(()=>expect(fetchMock.mock.calls.filter(([input])=>String(input).includes('/start'))).toHaveLength(1));expect(await screen.findByText('Renderização em andamento')).toBeInTheDocument();
  });

  it('falha no start mantém QUEUED explicado e permite cancelar',async()=>{
    const queued={...completed,id:'orphan',status:'QUEUED',validationStatus:null,progressPercent:0,currentStage:null};const canceled={...queued,status:'CANCELED',currentStage:'CANCELED'};const fetchMock=vi.fn(async(input:string|URL,init?:RequestInit)=>{const url=String(input);if(url.includes('/media-jobs?')||url.includes('/media-assets?'))return response([]);if(url.endsWith('/media/diagnostics'))return response(diagnostic);if(url.endsWith('/media-jobs/from-creative/cr1'))return response(queued,201);if(url.endsWith('/media-jobs/orphan/start'))return response({detail:'Preflight indisponível'},409);if(url.endsWith('/media-jobs/orphan/cancel')&&init?.method==='POST')return response(canceled);return response({})});vi.stubGlobal('fetch',controlledFetch(fetchMock));render(<MediaProduction creativeId="cr1" candidateId="candidate-1"/>);fireEvent.click(await screen.findByRole('button',{name:'Preparar preview'}));expect(await screen.findByText('Produção preparada')).toBeInTheDocument();fireEvent.click(screen.getByRole('button',{name:'Iniciar renderização'}));fireEvent.click(screen.getByRole('button',{name:'Confirmar início'}));expect(await screen.findByRole('alert')).toHaveTextContent('Não foi possível iniciar a produção. Verifique a configuração local de vídeo e voz.');expect(screen.getByText('Produção preparada')).toBeInTheDocument();expect(fetchMock.mock.calls.filter(([input])=>String(input).includes('/from-creative/'))).toHaveLength(1);fireEvent.click(screen.getByRole('button',{name:'Cancelar produção'}));expect(await screen.findByRole('group',{name:'Confirmar cancelamento da produção'})).toBeInTheDocument();fireEvent.click(screen.getByRole('button',{name:'Confirmar cancelamento'}));await waitFor(()=>expect(fetchMock).toHaveBeenCalledWith(expect.stringContaining('/media-jobs/orphan/cancel'),expect.objectContaining({method:'POST'})));expect(screen.getByText('Produção cancelada')).toBeInTheDocument();
  });
  it('ACTIVE_JOB_CONFLICT identifica a produção ativa e bloqueia nova preparação',async()=>{
    const active={...completed,id:'active-standard',renderType:'STANDARD',status:'RENDERING_AUDIO',progressPercent:24,currentStage:'RENDERING_AUDIO',attemptNumber:1};
    const fetchMock=vi.fn(async(input:string|URL)=>{const url=String(input);if(url.includes('/media-jobs?'))return response([active]);if(url.includes('/media-assets?'))return response([]);if(url.endsWith('/media/diagnostics'))return response(diagnostic);if(url.includes('/media-handoff'))return response({...handoff('ACTIVE_JOB_CONFLICT',active),renderType:url.includes('STANDARD')?'STANDARD':'PREVIEW'});return response({})});
    vi.stubGlobal('fetch',fetchMock);render(<MemoryRouter><MediaProduction creativeId="cr1" candidateId="candidate-1"/></MemoryRouter>);
    const conflictHeading=await screen.findByText('Já existe uma produção ativa para este criativo');expect(conflictHeading).toBeInTheDocument();expect(conflictHeading.parentElement?.querySelector('p')).toHaveTextContent('Vídeo final · Gerando áudio · tentativa 1');expect(screen.getByRole('button',{name:'Ver produção ativa'})).toBeInTheDocument();expect(screen.queryByRole('button',{name:'Preparar preview'})).not.toBeInTheDocument();expect(screen.queryByRole('button',{name:'Iniciar renderização'})).not.toBeInTheDocument();expect(fetchMock.mock.calls.some(([url])=>String(url).includes('/from-creative/'))).toBe(false);
    fireEvent.click(screen.getByRole('button',{name:'Ver produção ativa'}));await waitFor(()=>expect(fetchMock).toHaveBeenCalledWith(expect.stringContaining('media-handoff?renderType=STANDARD'),undefined));
  });
  it('MULTIPLE_ACTIVE_JOBS não escolhe job nem oferece criar/iniciar',async()=>{
    const jobs=[{...completed,id:'active-1',status:'PREPARING'},{...completed,id:'active-2',status:'COMPOSING'}];const fetchMock=vi.fn(async(input:string|URL)=>{const url=String(input);if(url.includes('/media-jobs?'))return response(jobs);if(url.includes('/media-assets?'))return response([]);if(url.endsWith('/media/diagnostics'))return response(diagnostic);if(url.includes('/media-handoff'))return response({...handoff('MULTIPLE_ACTIVE_JOBS'),mediaJobId:null,mediaJobStatus:null});return response({})});
    vi.stubGlobal('fetch',fetchMock);render(<MemoryRouter><MediaProduction creativeId="cr1" candidateId="candidate-1"/></MemoryRouter>);
    expect(await screen.findByText('Encontramos mais de uma produção ativa')).toBeInTheDocument();expect(screen.getByText('Atualize a página. Se o problema continuar, revise o histórico técnico.')).toBeInTheDocument();expect(screen.queryByRole('button',{name:/Preparar|Iniciar/})).not.toBeInTheDocument();expect(fetchMock.mock.calls.some(([url])=>String(url).includes('/from-creative/')||/\/start$/.test(String(url)))).toBe(false);
  });
  it('NOT_ELIGIBLE mostra blocker em linguagem humana e não cria job',async()=>{
    const fetchMock=vi.fn(async(input:string|URL)=>{const url=String(input);if(url.includes('/media-jobs?')||url.includes('/media-assets?'))return response([]);if(url.endsWith('/media/diagnostics'))return response(diagnostic);if(url.includes('/media-handoff'))return response({...handoff('NOT_ELIGIBLE'),reasonCode:'CREATIVE_APPROVAL_REQUIRED',blockers:[{code:'CREATIVE_APPROVAL_REQUIRED',message:'A aprovação do criativo precisa estar registrada.'}]});return response({})});
    vi.stubGlobal('fetch',fetchMock);render(<MemoryRouter><MediaProduction creativeId="cr1" candidateId="candidate-1"/></MemoryRouter>);
    expect(await screen.findByRole('heading',{name:'Produção indisponível'})).toBeInTheDocument();expect(screen.getByText('A aprovação do criativo precisa estar registrada.')).toBeInTheDocument();expect(screen.queryByRole('button',{name:/Preparar|Iniciar/})).not.toBeInTheDocument();expect(fetchMock.mock.calls.some(([url])=>String(url).includes('/from-creative/'))).toBe(false);
  });
  it('renderiza ações reais e permite ativar, desativar e remover',async()=>{
    const active={id:'asset-active',assetType:'PRODUCT_IMAGE',ownerType:'CANDIDATE',ownerId:'candidate-1',logicalName:'Produto ativo',relativePath:'assets/active.png',mimeType:'image/png',width:2,height:3,fileSizeBytes:32,metadata:{},active:true,createdAt:'2026-09-21T12:00:00Z',updatedAt:'2026-09-21T12:00:00Z'},inactive={...active,id:'asset-inactive',logicalName:'Produto inativo',relativePath:'assets/inactive.png',active:false};
    const fetchMock=vi.fn(async(input:string|URL,init?:RequestInit)=>{const url=String(input);if(url.includes('/media-jobs?'))return response([]);if(url.includes('/media-assets?')&&url.includes('active=true'))return response([active]);if(url.includes('/media-assets?')&&url.includes('active=false'))return response([inactive]);if(url.endsWith('/media/diagnostics'))return response(diagnostic);if(url.endsWith('/media-assets/asset-inactive/activate')&&init?.method==='POST')return response({...inactive,active:true});if(url.endsWith('/media-assets/asset-active')&&init?.method==='DELETE')return response({...active,active:false});if(url.endsWith('/media-assets/asset-inactive/permanent')&&init?.method==='DELETE')return new Response(null,{status:204});return response({})});vi.stubGlobal('fetch',controlledFetch(fetchMock));render(<MediaProduction creativeId="cr1" candidateId="candidate-1"/>);
    const activeCard=(await screen.findByText('Produto ativo')).closest('article')!,inactiveCard=screen.getByText('Produto inativo').closest('article')!;expect(activeCard).toHaveTextContent('Ativo');expect(activeCard).toHaveTextContent('Desativar');expect(activeCard).toHaveTextContent('Remover');expect(activeCard).not.toHaveTextContent('Ativar');expect(inactiveCard).toHaveTextContent('Inativo');expect(inactiveCard).toHaveTextContent('Ativar');expect(inactiveCard).toHaveTextContent('Remover');expect(inactiveCard).not.toHaveTextContent('Desativar');
    fireEvent.click(screen.getByRole('button',{name:'Ativar'}));await waitFor(()=>expect(fetchMock).toHaveBeenCalledWith(expect.stringContaining('/media-assets/asset-inactive/activate'),expect.objectContaining({method:'POST'})));expect(screen.getByText('Produto inativo').closest('article')).toHaveTextContent('Ativo');
    fireEvent.click(activeCard.querySelector('button')!);await waitFor(()=>expect(fetchMock).toHaveBeenCalledWith(expect.stringMatching(/media-assets\/asset-active$/),expect.objectContaining({method:'DELETE'})));await waitFor(()=>expect(screen.getByText('Produto ativo').closest('article')).toHaveTextContent('Inativo'));
    fireEvent.click(screen.getByText('Produto inativo').closest('article')!.querySelector('.danger-button')!);expect(screen.getByRole('alertdialog')).toHaveTextContent('Remover esta mídia permanentemente?');fireEvent.click(screen.getByRole('alertdialog').querySelector('.danger-button')!);await waitFor(()=>expect(fetchMock).toHaveBeenCalledWith(expect.stringContaining('/media-assets/asset-inactive/permanent'),expect.objectContaining({method:'DELETE'})));expect(screen.queryByText('Produto inativo')).not.toBeInTheDocument();
  });
  it('mostra status amigável, duração validada, player, download e diagnóstico sem detalhes do provider',async()=>{
    const fetchMock=vi.fn(async(input:string|URL)=>{const url=String(input);if(url.includes('/media-jobs?'))return response([completed]);if(url.includes('/media-assets?'))return response([]);if(url.endsWith('/media/diagnostics'))return response(diagnostic);return response({})});vi.stubGlobal('fetch',controlledFetch(fetchMock));
    render(<MediaProduction creativeId="cr1" candidateId="candidate-1"/>);
    expect((await screen.findAllByText('Concluída')).length).toBeGreaterThan(0);expect(screen.getAllByText('29.9 s')).toHaveLength(2);expect(screen.getByText('Voz').parentElement).toHaveTextContent('Não configurada');expect(screen.queryByText(/Piper|codec|540x960/i)).not.toBeInTheDocument();expect(document.querySelector('video')?.getAttribute('src')).toContain('/media-jobs/job-1/content');expect(screen.getByRole('link',{name:'Baixar vídeo'})).toHaveAttribute('href',expect.stringContaining('download=true'));
  });

  it('cria e inicia preview somente após ação do operador',async()=>{
    const queued={...completed,id:'job-2',status:'QUEUED',validationStatus:null,progressPercent:0,currentStage:null};const fetchMock=vi.fn(async(input:string|URL)=>{const url=String(input);if(url.includes('/media-jobs?'))return response([]);if(url.includes('/media-assets?'))return response([]);if(url.endsWith('/media/diagnostics'))return response(diagnostic);if(url.endsWith('/media-jobs/from-creative/cr1'))return response(queued,201);return response({})});vi.stubGlobal('fetch',controlledFetch(fetchMock));render(<MediaProduction creativeId="cr1" candidateId="candidate-1"/>);expect(await screen.findByText('Produção pronta para ser preparada')).toBeInTheDocument();expect(fetchMock).not.toHaveBeenCalledWith(expect.stringContaining('/from-creative/'),expect.anything());fireEvent.click(screen.getByRole('button',{name:'Preparar preview'}));await waitFor(()=>expect(fetchMock).toHaveBeenCalledWith(expect.stringContaining('/media-jobs/from-creative/cr1'),expect.objectContaining({body:JSON.stringify({renderType:'PREVIEW'})})));expect(await screen.findByText('Produção preparada')).toBeInTheDocument();expect(fetchMock.mock.calls.some(([input])=>String(input).includes('/start'))).toBe(false);
  });

  it('falha amigável permite tentar novamente criando um novo job',async()=>{
    const failed={...completed,id:'failed',status:'FAILED',validationStatus:null,errorMessage:'Não foi possível renderizar uma das cenas.',currentStage:'FAILED'};const fetchMock=vi.fn(async(input:string|URL)=>{const url=String(input);if(url.includes('/media-jobs?'))return response([failed]);if(url.includes('/media-assets?'))return response([]);if(url.endsWith('/media/diagnostics'))return response(diagnostic);if(url.endsWith('/media-jobs/from-creative/cr1'))return response({...failed,id:'new-job',status:'QUEUED'},201);return response({})});vi.stubGlobal('fetch',controlledFetch(fetchMock));render(<MediaProduction creativeId="cr1" candidateId="candidate-1"/>);expect(await screen.findByText('Não foi possível concluir a produção')).toBeInTheDocument();expect(screen.getByText(/Não foi possível renderizar uma das cenas/)).toBeInTheDocument();fireEvent.click(screen.getByRole('button',{name:'Preparar nova tentativa'}));await waitFor(()=>expect(fetchMock).toHaveBeenCalledWith(expect.stringContaining('/media-jobs/from-creative/cr1'),expect.objectContaining({method:'POST'})));expect(await screen.findByText('Produção preparada')).toBeInTheDocument();expect(fetchMock.mock.calls.some(([input])=>String(input).includes('/start'))).toBe(false);
  });
  it('classifica avatar com personagem e expressão em português',async()=>{
    const uploaded={id:'avatar-1',assetType:'AVATAR_IMAGE',logicalName:'bruno.png',mimeType:'image/png',metadata:{speaker:'BRUNO',state:'WARNING',hasAlpha:true},active:true,createdAt:'2026-09-23T12:00:00Z'};
    const fetchMock=vi.fn(async(input:string|URL,init?:RequestInit)=>{const url=String(input);if(url.includes('/media-jobs?')||url.includes('/media-assets?'))return response([]);if(url.endsWith('/media/diagnostics'))return response(diagnostic);if(url.endsWith('/media-assets')&&init?.method==='POST'){const form=init.body as FormData;expect(form.get('character')).toBe('BRUNO');expect(form.get('avatarState')).toBe('WARNING');expect(form.get('ownerType')).toBe('AVATAR');return response(uploaded,201)}return response({})});vi.stubGlobal('fetch',controlledFetch(fetchMock));render(<MediaProduction creativeId="cr1" candidateId="candidate-1"/>);expect(await screen.findByText('Produção pronta para ser preparada')).toBeInTheDocument();fireEvent.change(screen.getByLabelText('Tipo'),{target:{value:'AVATAR_IMAGE'}});expect(screen.getByLabelText('Personagem')).toBeInTheDocument();fireEvent.change(screen.getByLabelText('Expressão'),{target:{value:'WARNING'}});fireEvent.change(screen.getByLabelText('Arquivo'),{target:{files:[new File(['png'],'bruno.png',{type:'image/png'})]}});fireEvent.submit(screen.getByRole('button',{name:'Enviar mídia'}).closest('form')!);expect(await screen.findByText('bruno.png')).toBeInTheDocument();expect(screen.getByText(/Bruno · Alerta/)).toBeInTheDocument();
  });
  it('mostra bundle, classificação e grupo duplicado em linguagem humana',async()=>{
    const asset={id:'product-1',assetType:'PRODUCT_IMAGE',ownerType:'CANDIDATE',ownerId:'candidate-1',logicalName:'produto.png',mimeType:'image/png',width:456,height:465,metadata:{classification:'HERO_IMAGE'},active:true,createdAt:'2026-09-23T12:00:00Z'};
    const bundle={ownerId:'candidate-1',assetCount:1,uniqueVisualGroups:1,videoCount:0,detailCount:0,heroCount:1,diversityScore:20,diversityLevel:'LOW',qualityCheck:'WARNING',warning:'Limited source media',assets:[{assetId:'product-1',mediaType:'PRODUCT_IMAGE',width:456,height:465,aspectRatio:.981,hasAlpha:false,classification:'HERO_IMAGE',confidence:'HIGH',qualityScore:50,visualFingerprint:'dh:0',duplicateGroup:'PRODUCT_MEDIA_01',usableFor:['GENERAL'],warnings:[]}]};
    const fetchMock=vi.fn(async(input:string|URL)=>{const url=String(input);if(url.includes('/media-jobs?'))return response([]);if(url.includes('/media-assets?'))return response([asset]);if(url.endsWith('/media/diagnostics'))return response(diagnostic);if(url.includes('/product-media-bundles/'))return response(bundle);return response({})});vi.stubGlobal('fetch',controlledFetch(fetchMock));render(<MediaProduction creativeId="cr1" candidateId="candidate-1"/>);
    expect(await screen.findByText('Baixa')).toBeInTheDocument();expect(screen.getByText('Principal')).toBeInTheDocument();expect(screen.getByText('456 × 465')).toBeInTheDocument();expect(screen.getByText('Manual/Outra origem')).toBeInTheDocument();expect(screen.getAllByText(/Material visual limitado/i).length).toBeGreaterThan(0);
  });
});
