"""V1-A foundation tables."""
from alembic import op
import sqlalchemy as sa
revision = "0001_v1a"
down_revision = None

def upgrade():
    op.create_table("app_settings", sa.Column("id", sa.Integer(), primary_key=True), sa.Column("monthly_confirmed_commission_goal_cents", sa.Integer(), nullable=False), sa.Column("daily_publication_limit", sa.Integer(), nullable=False), sa.Column("timezone", sa.String(64), nullable=False), sa.Column("system_automation_enabled", sa.Boolean(), nullable=False), sa.Column("radar_enabled", sa.Boolean(), nullable=False), sa.Column("creative_enabled", sa.Boolean(), nullable=False), sa.Column("publishing_enabled", sa.Boolean(), nullable=False), sa.Column("comment_reply_enabled", sa.Boolean(), nullable=False), sa.Column("external_intelligence_enabled", sa.Boolean(), nullable=False), sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False))
    op.create_table("approvals", sa.Column("id", sa.String(36), primary_key=True), sa.Column("type", sa.String(24), nullable=False), sa.Column("status", sa.String(24), nullable=False), sa.Column("title", sa.String(200), nullable=False), sa.Column("description", sa.Text(), nullable=False), sa.Column("entity_type", sa.String(80)), sa.Column("entity_id", sa.String(36)), sa.Column("requested_payload", sa.JSON()), sa.Column("decided_at", sa.DateTime(timezone=True)), sa.Column("decision_reason", sa.Text()), sa.Column("is_demo", sa.Boolean(), nullable=False, server_default=sa.false()), sa.Column("created_at", sa.DateTime(timezone=True), nullable=False), sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False))
    op.create_index("idx_approvals_status_created", "approvals", ["status", "created_at"])
    op.create_table("notifications", sa.Column("id", sa.String(36), primary_key=True), sa.Column("type", sa.String(80), nullable=False), sa.Column("severity", sa.String(24), nullable=False), sa.Column("title", sa.String(200), nullable=False), sa.Column("message", sa.Text(), nullable=False), sa.Column("is_read", sa.Boolean(), nullable=False), sa.Column("created_at", sa.DateTime(timezone=True), nullable=False), sa.Column("read_at", sa.DateTime(timezone=True)), sa.Column("metadata", sa.JSON()), sa.Column("is_demo", sa.Boolean(), nullable=False, server_default=sa.false()))
    op.create_index("idx_notifications_read_created", "notifications", ["is_read", "created_at"])
    op.create_table("agent_tasks", sa.Column("id", sa.String(36), primary_key=True), sa.Column("type", sa.String(80), nullable=False), sa.Column("status", sa.String(24), nullable=False), sa.Column("title", sa.String(200), nullable=False), sa.Column("payload", sa.JSON()), sa.Column("result", sa.JSON()), sa.Column("error", sa.Text()), sa.Column("is_automatic", sa.Boolean(), nullable=False), sa.Column("is_demo", sa.Boolean(), nullable=False, server_default=sa.false()), sa.Column("created_at", sa.DateTime(timezone=True), nullable=False), sa.Column("started_at", sa.DateTime(timezone=True)), sa.Column("finished_at", sa.DateTime(timezone=True)), sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False))
    op.create_index("idx_tasks_status_created", "agent_tasks", ["status", "created_at"])
    op.create_table("decision_logs", sa.Column("id", sa.String(36), primary_key=True), sa.Column("timestamp", sa.DateTime(timezone=True), nullable=False), sa.Column("actor", sa.String(80), nullable=False), sa.Column("entity_type", sa.String(80), nullable=False), sa.Column("entity_id", sa.String(36)), sa.Column("action", sa.String(120), nullable=False), sa.Column("reason", sa.Text()), sa.Column("confidence", sa.String(24)), sa.Column("metadata", sa.JSON()), sa.Column("is_demo", sa.Boolean(), nullable=False, server_default=sa.false()))
    op.create_index("idx_decisions_timestamp", "decision_logs", ["timestamp"])
    op.create_index("idx_decisions_actor_entity", "decision_logs", ["actor", "entity_type"])
    op.execute("INSERT INTO app_settings (id, monthly_confirmed_commission_goal_cents, daily_publication_limit, timezone, system_automation_enabled, radar_enabled, creative_enabled, publishing_enabled, comment_reply_enabled, external_intelligence_enabled, updated_at) VALUES (1, 100000, 20, 'America/Sao_Paulo', 1, 0, 0, 0, 0, 0, CURRENT_TIMESTAMP)")

def downgrade():
    op.drop_table("decision_logs"); op.drop_table("agent_tasks"); op.drop_table("notifications"); op.drop_table("approvals"); op.drop_table("app_settings")
