"""campaign engine
Revision ID: 0006_campaign_engine
Revises: 0005_curator_assessments
"""
from alembic import op
import sqlalchemy as sa
revision="0006_campaign_engine";down_revision="0005_curator_assessments";branch_labels=None;depends_on=None
def upgrade():
    op.create_table("campaigns",sa.Column("id",sa.String(36),primary_key=True),sa.Column("candidate_id",sa.String(36),sa.ForeignKey("curator_candidates.id"),nullable=False),sa.Column("assessment_id",sa.String(36),sa.ForeignKey("curator_assessments.id"),nullable=False),sa.Column("name",sa.String(200),nullable=False),sa.Column("status",sa.String(24),nullable=False),sa.Column("objective",sa.String(24),nullable=False),sa.Column("editorial_verdict_snapshot",sa.String(40),nullable=False),sa.Column("trust_gate_snapshot",sa.String(32),nullable=False),sa.Column("recommendation_score_snapshot",sa.Integer),sa.Column("opportunity_score_snapshot",sa.Integer),sa.Column("price_verdict_snapshot",sa.String(32),nullable=False),sa.Column("campaign_priority",sa.String(16),nullable=False),sa.Column("target_audience",sa.Text),sa.Column("editorial_positioning",sa.Text),sa.Column("primary_message",sa.Text),sa.Column("affiliate_url",sa.String(2000)),sa.Column("affiliate_url_source",sa.String(24),nullable=False),sa.Column("affiliate_url_verified_at",sa.DateTime(timezone=True)),sa.Column("disclosure_text",sa.Text,nullable=False),sa.Column("cta_strategy",sa.Text),sa.Column("requires_financial_spend",sa.Boolean,nullable=False,server_default=sa.false()),sa.Column("trust_warnings_snapshot",sa.JSON,nullable=False),sa.Column("required_disclosures",sa.JSON,nullable=False),sa.Column("required_warnings",sa.JSON,nullable=False),sa.Column("forbidden_claims",sa.JSON,nullable=False),sa.Column("created_at",sa.DateTime(timezone=True),nullable=False),sa.Column("updated_at",sa.DateTime(timezone=True),nullable=False),sa.Column("approved_at",sa.DateTime(timezone=True)),sa.Column("rejected_at",sa.DateTime(timezone=True)))
    op.create_table("campaign_channels",sa.Column("id",sa.String(36),primary_key=True),sa.Column("campaign_id",sa.String(36),sa.ForeignKey("campaigns.id",ondelete="CASCADE"),nullable=False),sa.Column("channel",sa.String(32),nullable=False),sa.Column("enabled",sa.Boolean,nullable=False),sa.Column("publication_mode",sa.String(32),nullable=False),sa.Column("platform_notes",sa.Text),sa.Column("created_at",sa.DateTime(timezone=True),nullable=False),sa.Column("updated_at",sa.DateTime(timezone=True),nullable=False))
    op.create_table("campaign_angles",sa.Column("id",sa.String(36),primary_key=True),sa.Column("campaign_id",sa.String(36),sa.ForeignKey("campaigns.id",ondelete="CASCADE"),nullable=False),sa.Column("angle_type",sa.String(32),nullable=False),sa.Column("title",sa.String(200),nullable=False),sa.Column("premise",sa.Text,nullable=False),sa.Column("target_segment",sa.Text),sa.Column("priority",sa.Integer,nullable=False),sa.Column("status",sa.String(16),nullable=False),sa.Column("created_at",sa.DateTime(timezone=True),nullable=False),sa.Column("updated_at",sa.DateTime(timezone=True),nullable=False))
    op.create_table("campaign_experiments",sa.Column("id",sa.String(36),primary_key=True),sa.Column("campaign_id",sa.String(36),sa.ForeignKey("campaigns.id",ondelete="CASCADE"),nullable=False),sa.Column("angle_id",sa.String(36),sa.ForeignKey("campaign_angles.id")),sa.Column("hypothesis",sa.Text,nullable=False),sa.Column("status",sa.String(24),nullable=False),sa.Column("hook_strategy",sa.Text),sa.Column("cta_strategy",sa.Text),sa.Column("target_channel",sa.String(32)),sa.Column("variant_group",sa.String(80)),sa.Column("parent_experiment_id",sa.String(36),sa.ForeignKey("campaign_experiments.id")),sa.Column("created_at",sa.DateTime(timezone=True),nullable=False),sa.Column("updated_at",sa.DateTime(timezone=True),nullable=False))
def downgrade():
    op.drop_table("campaign_experiments");op.drop_table("campaign_angles");op.drop_table("campaign_channels");op.drop_table("campaigns")
