"""creative studio
Revision ID: 0007_creative_studio
Revises: 0006_campaign_engine
"""
from alembic import op
import sqlalchemy as sa
revision="0007_creative_studio";down_revision="0006_campaign_engine";branch_labels=None;depends_on=None
def upgrade():
    op.create_table("creatives",sa.Column("id",sa.String(36),primary_key=True),sa.Column("campaign_id",sa.String(36),sa.ForeignKey("campaigns.id"),nullable=False),sa.Column("experiment_id",sa.String(36),sa.ForeignKey("campaign_experiments.id")),sa.Column("name",sa.String(200),nullable=False),sa.Column("status",sa.String(24),nullable=False),sa.Column("content_type",sa.String(32),nullable=False),sa.Column("target_channel",sa.String(32),nullable=False),sa.Column("angle_type_snapshot",sa.String(32)),sa.Column("objective_snapshot",sa.String(24),nullable=False),sa.Column("editorial_verdict_snapshot",sa.String(40),nullable=False),sa.Column("price_verdict_snapshot",sa.String(32),nullable=False),sa.Column("title",sa.String(300)),sa.Column("content_premise",sa.Text),sa.Column("hook",sa.Text),sa.Column("body_script",sa.Text),sa.Column("cta",sa.Text),sa.Column("estimated_duration_seconds",sa.Integer),sa.Column("disclosure_text",sa.Text,nullable=False),sa.Column("required_warnings",sa.JSON,nullable=False),sa.Column("forbidden_claims",sa.JSON,nullable=False),sa.Column("generation_mode",sa.String(32),nullable=False),sa.Column("variant_group",sa.String(80)),sa.Column("parent_creative_id",sa.String(36),sa.ForeignKey("creatives.id")),sa.Column("variant_label",sa.String(40)),sa.Column("created_at",sa.DateTime(timezone=True),nullable=False),sa.Column("updated_at",sa.DateTime(timezone=True),nullable=False),sa.Column("approved_at",sa.DateTime(timezone=True)),sa.Column("rejected_at",sa.DateTime(timezone=True)))
    op.create_table("creative_scenes",sa.Column("id",sa.String(36),primary_key=True),sa.Column("creative_id",sa.String(36),sa.ForeignKey("creatives.id",ondelete="CASCADE"),nullable=False),sa.Column("order_index",sa.Integer,nullable=False),sa.Column("scene_type",sa.String(24),nullable=False),sa.Column("speaker",sa.String(16),nullable=False),sa.Column("purpose",sa.String(120),nullable=False),sa.Column("narration_text",sa.Text),sa.Column("on_screen_text",sa.Text),sa.Column("visual_instruction",sa.Text),sa.Column("avatar_state",sa.String(24)),sa.Column("duration_seconds",sa.Integer),sa.Column("required_warning_codes",sa.JSON,nullable=False),sa.Column("created_at",sa.DateTime(timezone=True),nullable=False),sa.Column("updated_at",sa.DateTime(timezone=True),nullable=False))
def downgrade():op.drop_table("creative_scenes");op.drop_table("creatives")
