"""local media engine
Revision ID: 0008_local_media_engine
Revises: 0007_creative_studio
"""
from alembic import op
import sqlalchemy as sa
revision="0008_local_media_engine";down_revision="0007_creative_studio";branch_labels=None;depends_on=None
def upgrade():
    op.create_table("media_jobs",sa.Column("id",sa.String(36),primary_key=True),sa.Column("creative_id",sa.String(36),sa.ForeignKey("creatives.id"),nullable=False),sa.Column("render_type",sa.String(16),nullable=False),sa.Column("status",sa.String(32),nullable=False),sa.Column("width",sa.Integer,nullable=False),sa.Column("height",sa.Integer,nullable=False),sa.Column("fps",sa.Integer,nullable=False),sa.Column("video_codec",sa.String(24),nullable=False),sa.Column("audio_codec",sa.String(24),nullable=False),sa.Column("expected_duration_seconds",sa.Integer),sa.Column("actual_duration_seconds",sa.Integer),sa.Column("output_relative_path",sa.String(500)),sa.Column("preview_relative_path",sa.String(500)),sa.Column("output_size_bytes",sa.Integer),sa.Column("validation_status",sa.String(16)),sa.Column("validation_details",sa.JSON),sa.Column("progress_percent",sa.Integer,nullable=False),sa.Column("current_stage",sa.String(40)),sa.Column("current_scene_index",sa.Integer),sa.Column("total_scenes",sa.Integer),sa.Column("error_code",sa.String(80)),sa.Column("error_message",sa.Text),sa.Column("created_at",sa.DateTime(timezone=True),nullable=False),sa.Column("started_at",sa.DateTime(timezone=True)),sa.Column("completed_at",sa.DateTime(timezone=True)),sa.Column("updated_at",sa.DateTime(timezone=True),nullable=False))
    op.create_table("media_assets",sa.Column("id",sa.String(36),primary_key=True),sa.Column("asset_type",sa.String(24),nullable=False),sa.Column("owner_type",sa.String(24),nullable=False),sa.Column("owner_id",sa.String(36)),sa.Column("logical_name",sa.String(200),nullable=False),sa.Column("relative_path",sa.String(500),nullable=False,unique=True),sa.Column("mime_type",sa.String(80),nullable=False),sa.Column("width",sa.Integer),sa.Column("height",sa.Integer),sa.Column("file_size_bytes",sa.Integer,nullable=False),sa.Column("metadata",sa.JSON),sa.Column("active",sa.Boolean,nullable=False),sa.Column("created_at",sa.DateTime(timezone=True),nullable=False),sa.Column("updated_at",sa.DateTime(timezone=True),nullable=False))
def downgrade():op.drop_table("media_assets");op.drop_table("media_jobs")
