import{useCallback,useEffect,useState}from'react';
import{Link,useLocation,useNavigate,useParams}from'react-router-dom';
import{creativesApi}from'../api/creatives';import{campaignsApi}from'../api/campaigns';
import{Badge,Empty,ErrorState,Loading,Section}from'../components/ui';import{CreativeSceneEditor}from'../components/CreativeSceneEditor';import{CreativeApprovalActions}from'../components/CreativeApprovalActions';
import{useLoad}from'../hooks';import{creativeStatusLabel,label,statusTone}from'../lib/presentation';

export function CreativesPage(){
 const load=useCallback(()=>creativesApi.list(),[]);const{data,error,loading,refresh}=useLoad(load);
 if(loading)return <Loading/>;if(error||!data)return <ErrorState error={error??new Error('Erro')} retry={refresh}/>;const count=(s:string)=>data.filter(x=>x.status===s).length;
 return <><header className="page-head"><div><span>CREATIVE STUDIO</span><h1>Criativos</h1><p>Estruturas textuais aprovadas antes de qualquer renderização.</p></div></header><div className="metric-grid">{[['DRAFT','Rascunhos'],['READY_FOR_REVIEW','Em revisão'],['APPROVED','Aprovados'],['REJECTED','Rejeitados']].map(([s,t])=><div key={s}><b>{count(s)}</b><span>{t}</span></div>)}</div><Section title="Criativos">{data.length?<div className="compact-list">{data.map(x=><Link key={x.id} to={'/criativos/'+x.id}><span><b>{x.name}</b><small>{label(x.contentType)} · {label(x.targetChannel)} · {x.hook||'Hook pendente'}</small></span><Badge tone={statusTone(x.status)}>{creativeStatusLabel(x.status)}</Badge></Link>)}</div>:<Empty>Nenhum criativo criado.</Empty>}</Section></>;
}

const empty={title:'',premise:'',hook:'',body:'',cta:'',duration:'20',channel:'GENERIC'};
export function CreativePage(){
 const{id=''}=useParams();const nav=useNavigate();const location=useLocation();
 const load=useCallback(async()=>{const[c,scenes,ready,direction]=await Promise.all([creativesApi.get(id),creativesApi.scenes(id),creativesApi.readiness(id),creativesApi.direction(id)]);const campaign=await campaignsApi.get(c.campaignId);return{c,scenes,ready,direction,campaign}},[id]);
 const{data,error,loading,refresh}=useLoad(load);const[draft,setDraft]=useState(empty);const[initializedId,setInitializedId]=useState('');const[state,setState]=useState('');const[templateError,setTemplateError]=useState('');const[duplicateError,setDuplicateError]=useState('');const[duplicating,setDuplicating]=useState(false);const[tiktokBusy,setTiktokBusy]=useState(false);
 useEffect(()=>{if(data&&initializedId!==id){const c=data.c;setDraft({title:c.title??'',premise:c.contentPremise??'',hook:c.hook??'',body:c.bodyScript??'',cta:c.cta??'',duration:String(c.estimatedDurationSeconds??20),channel:c.targetChannel});setInitializedId(id);setState('')}},[data,id,initializedId]);
 if(loading)return <Loading/>;if(error||!data)return <ErrorState error={error??new Error('Erro')} retry={refresh}/>;
 const{c,scenes,ready,direction,campaign}=data;const editable=['DRAFT','REJECTED'].includes(c.status);const readOnlyMessage=c.status==='APPROVED'?'Criativo aprovado — conteúdo bloqueado para edição.':c.status==='READY_FOR_REVIEW'?'Criativo em revisão — aguarde a decisão para editar novamente.':c.status==='ARCHIVED'?'Criativo arquivado — conteúdo somente para consulta.':'';
 const set=(k:string,v:string)=>{if(!editable)return;setDraft(x=>({...x,[k]:v}));setState('Não salvo')};
 const save=async()=>{setState('Salvando…');try{await creativesApi.patch(id,{title:draft.title,contentPremise:draft.premise,hook:draft.hook,bodyScript:draft.body,cta:draft.cta,estimatedDurationSeconds:Number(draft.duration),targetChannel:draft.channel});setState('Salvo');refresh()}catch(e){setState(e instanceof Error?e.message:'Falha ao salvar')}};
 const duplicate=async()=>{if(duplicating)return;setDuplicating(true);setDuplicateError('');try{const copy=await creativesApi.duplicate(id);nav('/criativos/'+copy.id,{state:{notice:'Cópia criada. Você pode editar este Creative.'}})}catch(e){setDuplicateError(e instanceof Error?e.message:'Não foi possível criar a cópia editável.')}finally{setDuplicating(false)}};
 return <>
  <header className="page-head"><div><span>CREATIVE STUDIO</span><h1>{c.name}</h1><p>Nenhuma mídia, publicação ou gasto ocorre nesta fase.</p></div><div className="page-head-actions"><Badge tone={statusTone(c.status)}>{creativeStatusLabel(c.status)}</Badge><CreativeApprovalActions creativeId={id} status={c.status} onChanged={refresh}/></div></header>
  {(location.state as{notice?:string}|null)?.notice&&<p className="readonly-notice" role="status">{(location.state as{notice?:string}).notice}</p>}
  <Section title="Resumo"><div className="campaign-summary">{[['Campanha',campaign.name],['Experimento',c.experimentId?'Experimento associado':'Sem experimento'],['Formato',label(c.contentType)],['Canal',label(c.targetChannel)],['Ângulo',c.angleTypeSnapshot?label(c.angleTypeSnapshot):'Sem ângulo definido'],['Status',creativeStatusLabel(c.status)]].map(([k,v])=><div key={k}><small>{k}</small><b>{v}</b></div>)}</div></Section>
  <Section title="Direção criativa"><div className="campaign-summary">{[['Persona',direction.persona?label(direction.persona):'Não definida'],['Ângulo',direction.creativeAngle?label(direction.creativeAngle):'Não definido'],['Tipo de gancho',direction.hookType?label(direction.hookType):'Não definido'],['CTA',direction.ctaType?label(direction.ctaType):'Não definido']].map(([k,v])=><div key={k}><small>{k}</small><b>{v}</b></div>)}</div><p><b>Gancho:</b> {direction.hookText||c.hook||'Pendente'}</p>{direction.angleReason&&<p className="timestamp">{direction.angleReason}</p>}<div className="source-status">{Object.entries(direction.qualityChecks??{}).map(([key,value])=><span key={key}><Badge tone={value==='PASS'?'success':value==='FAIL'?'danger':'warning'}>{label(value)}</Badge>{label(key)}</span>)}</div><div className="creative-storyboard">{(direction.storyboard??[]).map(scene=><article key={scene.sceneId??scene.orderIndex}><b>{scene.orderIndex+1}. {label(scene.purpose)}</b><p>{scene.scriptSegment}</p><small>{scene.speechSegmentId} · {scene.avatarSpeaker?label(scene.avatarSpeaker):'Sem personagem'} · {scene.recommendedDuration}s</small>{scene.visualUnits?.map(unit=><div className="visual-unit" key={unit.visualUnitIndex}><span>Visual {unit.visualUnitIndex+1}: {label(unit.visualIntent)}</span><small>{unit.onScreenText} · {unit.estimatedDuration}s</small></div>)}</article>)}</div>{c.status==='APPROVED'&&<button type="button" className="primary-button" disabled={tiktokBusy} onClick={async()=>{if(tiktokBusy)return;setTiktokBusy(true);setDuplicateError('');try{const copy=await creativesApi.tiktokVariant(id);nav('/criativos/'+copy.id,{state:{notice:'Versão TikTok-first criada para revisão e edição.'}})}catch(e){setDuplicateError(e instanceof Error?e.message:'Não foi possível criar a versão TikTok-first.')}finally{setTiktokBusy(false)}}}>{tiktokBusy?'Criando versão…':'Criar versão TikTok-first'}</button>}</Section>
  <Section title="Estratégia">{!editable&&readOnlyMessage&&<p className="readonly-notice">{readOnlyMessage}</p>}{c.status==='APPROVED'&&<button type="button" className="primary-button" disabled={duplicating} onClick={duplicate}>{duplicating?'Criando cópia…':'Criar cópia editável'}</button>}{duplicateError&&<p role="alert" className="inline-error">{duplicateError}</p>}<div className="campaign-form"><label>Título<input readOnly={!editable} value={draft.title} onChange={e=>set('title',e.target.value)}/></label><label>Canal<select disabled={!editable} value={draft.channel} onChange={e=>set('channel',e.target.value)}>{['GENERIC','TIKTOK','INSTAGRAM_REELS','YOUTUBE_SHORTS','FACEBOOK_REELS','WHATSAPP','WEBSITE'].map(x=><option key={x} value={x}>{label(x)}</option>)}</select></label><label>Premissa<textarea readOnly={!editable} value={draft.premise} onChange={e=>set('premise',e.target.value)}/></label><label>Hook<textarea readOnly={!editable} value={draft.hook} onChange={e=>set('hook',e.target.value)}/></label><label>Roteiro<textarea readOnly={!editable} value={draft.body} onChange={e=>set('body',e.target.value)}/></label><label>CTA<textarea readOnly={!editable} value={draft.cta} onChange={e=>set('cta',e.target.value)}/></label><label>Duração<select disabled={!editable} value={draft.duration} onChange={e=>set('duration',e.target.value)}>{[15,20,30,45,60].map(x=><option key={x}>{x}</option>)}</select></label></div>{editable&&<div className="campaign-savebar"><button type="button" className="primary-button" onClick={save}>Salvar criativo</button><span>{state||'Sem alterações pendentes'}</span><button type="button" className="ghost-button" onClick={async()=>{const overwrite=scenes.length>0;if(overwrite&&!confirm('Este criativo já possui uma estrutura. Gerar novamente substituirá o roteiro e as cenas atuais. Deseja continuar?'))return;setTemplateError('');try{const generated=await creativesApi.template(id,overwrite);setDraft({title:generated.title??'',premise:generated.contentPremise??'',hook:generated.hook??'',body:generated.bodyScript??'',cta:generated.cta??'',duration:String(generated.estimatedDurationSeconds??20),channel:generated.targetChannel});setState('Salvo');await refresh()}catch(e){setTemplateError(e instanceof Error?e.message:'Não foi possível gerar a estrutura inicial.')}}}>Gerar estrutura inicial</button></div>}{templateError&&<p role="alert" className="inline-error">{templateError}</p>}</Section>
  <Section title="Cenas">{editable&&<form className="diagnostic-controls" onSubmit={async e=>{e.preventDefault();const f=new FormData(e.currentTarget);await creativesApi.addScene(id,{orderIndex:scenes.length,sceneType:f.get('type'),speaker:f.get('speaker'),purpose:f.get('purpose'),narrationText:f.get('narration')||null});e.currentTarget.reset();refresh()}}><select name="type">{['AVATAR','PRODUCT','TEXT','COMPARISON','PROS_CONS','PRICE','WARNING','CTA','BROLL','MIXED'].map(x=><option key={x} value={x}>{label(x)}</option>)}</select><select name="speaker">{['BRUNO','CAROL','NARRATOR','NONE'].map(x=><option key={x} value={x}>{label(x)}</option>)}</select><input name="purpose" placeholder="Propósito" required/><input name="narration" placeholder="Narração"/><button type="submit">Adicionar cena</button></form>}<div className="compact-list">{scenes.map((scene,index)=><CreativeSceneEditor key={scene.id} creativeId={id} scene={scene} index={index} count={scenes.length} editable={editable} onRefresh={refresh}/>)}</div></Section>
  <Section title="Compliance"><h3>{label(ready.compliance.status)}</h3>{ready.compliance.reasons.map(x=><p className="inline-error" key={x.code}>{x.message}</p>)}{ready.compliance.requiredWarningCoverage.map(x=><p key={x.code}>{x.message}: <b>{label(x.status)}</b></p>)}<p><b>Disclosure:</b> {c.disclosureText}</p><div className="source-status">{c.forbiddenClaims.map(x=><span key={x}>{label(x)}</span>)}</div></Section>
  <Section title="Readiness e aprovação"><h3>{label(ready.state)}</h3><div className="source-status">{Object.entries(ready.checks).map(([k,v])=><span key={k}><Badge tone={v?'success':'warning'}>{v?'OK':'Pendente'}</Badge>{label(k)}</span>)}</div>{editable&&<button type="button" className="ghost-button" onClick={async()=>nav('/criativos/'+(await creativesApi.variant(id)).id)}>Duplicar como variante</button>}</Section><button type="button" className="ghost-button" onClick={()=>nav('/criativos')}>Voltar</button>
 </>;
}
