import{useCallback,useEffect,useMemo,useState}from'react';
import{Link,useParams}from'react-router-dom';
import{api}from'../api/client';
import{creativesApi}from'../api/creatives';
import{campaignsApi}from'../api/campaigns';
import{mediaApi,PublicationApiError}from'../api/media';
import type{ChannelVariant,InstagramConnection,MediaDeliveryPlan,PublicationExecution,PublicationReadiness,Settings,StaticCreativePlan}from'../types';
import{Badge,ErrorState,Loading,Section}from'../components/ui';
import{creativeStatusLabel,label,statusTone}from'../lib/presentation';
import'./InstagramPublish.css';

const blockerLabel:Record<string,string>={CHANNEL_VARIANT_REQUIRED:'Prepare a versão da imagem para o Instagram',DISCLOSURE_REQUIREMENT_UNKNOWN:'Confirme o disclosure de afiliado',APPROVAL_REQUIRED:'O Creative precisa estar aprovado',CREATIVE_NOT_APPROVED:'O Creative precisa estar aprovado',CHANNEL_COMPATIBILITY_UNRESOLVED:'A compatibilidade com o Instagram ainda não está resolvida',DESTINATION_URL_MISSING:'Informe uma URL de destino válida',AFFILIATE_URL_MISSING:'Informe uma URL de afiliado válida'};
const statusLabel:Record<string,string>={READY:'Pronto para publicar',READY_WITH_WARNINGS:'Pronto com avisos',BLOCKED:'Há pendências',CONNECTED:'Instagram conectado',PUBLISHED:'Publicado',PUBLISHING:'Publicando',PLANNED:'Planejado',FAILED:'Falha na publicação'};
const executionTone=(status:string)=>status==='PUBLISHED'?'success':status==='FAILED'?'danger':status==='PUBLISHING'?'warning':'info';
const sameFiles=(left:string[],right:string[])=>JSON.stringify(left)===JSON.stringify(right);
const deliveryUsable=(value:MediaDeliveryPlan|null)=>!!value&&value.readiness==='READY'&&!!value.hostedAssets?.length&&value.hostedAssets.every(asset=>Number.isFinite(Date.parse(asset.expiresAt))&&Date.parse(asset.expiresAt)>Date.now());

export function InstagramPublishPage(){
 const{id=''}=useParams();const[base,setBase]=useState<{creative:Awaited<ReturnType<typeof creativesApi.get>>;campaign:Awaited<ReturnType<typeof campaignsApi.get>>;connection:InstagramConnection;settings:Settings}|null>(null),[readiness,setReadiness]=useState<PublicationReadiness|null>(null),[variant,setVariant]=useState<ChannelVariant|null>(null),[staticResult,setStaticResult]=useState<StaticCreativePlan|null>(null),[packageData,setPackageData]=useState<PublicationReadiness|null>(null),[delivery,setDelivery]=useState<MediaDeliveryPlan|null>(null),[history,setHistory]=useState<PublicationExecution[]>([]),[retryTarget,setRetryTarget]=useState<PublicationExecution|null>(null),[busy,setBusy]=useState(''),[error,setError]=useState(''),[message,setMessage]=useState(''),[confirmOpen,setConfirmOpen]=useState(false),[confirmed,setConfirmed]=useState(false),[retryOpen,setRetryOpen]=useState(false),[retryConfirmed,setRetryConfirmed]=useState(false),[disclosure,setDisclosure]=useState('');
 const load=useCallback(async()=>{try{const[creative,connection,settings,current,variants,executions]=await Promise.all([creativesApi.get(id),mediaApi.instagramConnection(),api.settings(),mediaApi.publicationReadiness(id,{distributionMode:'ORGANIC',format:'STATIC_CARD',channel:'INSTAGRAM'}),mediaApi.channelVariants(id),mediaApi.publicationExecutions(id)]);const campaign=await campaignsApi.get(creative.campaignId);setBase({creative,campaign,connection,settings});setReadiness(current);setVariant(variants.find(x=>x.profile?.profileId==='INSTAGRAM_FEED_STATIC_CARD_V1')??null);setHistory(executions);setDisclosure(value=>value||creative.disclosureText||campaign.disclosureText||'Este conteúdo contém link de afiliado.')}catch(e){setError(e instanceof Error?e.message:'Não foi possível carregar o fluxo de publicação.')}},[id]);
 useEffect(()=>{void load();const refresh=()=>void load(),message=(event:MessageEvent)=>{if(event.origin===window.location.origin&&event.data?.type==='instagram-oauth-complete')void load()};window.addEventListener('focus',refresh);window.addEventListener('message',message);return()=>{window.removeEventListener('focus',refresh);window.removeEventListener('message',message)}},[load]);
 const run=async(name:string,action:()=>Promise<void>)=>{if(busy)return;setBusy(name);setError('');setMessage('');try{await action()}catch(e){setError(e instanceof Error?e.message:'Não foi possível concluir a ação.')}finally{setBusy('')}};
 const resetConfirmation=()=>{setConfirmOpen(false);setConfirmed(false);setRetryOpen(false);setRetryConfirmed(false);setRetryTarget(null)};
 const invalidateAfterStatic=()=>{setVariant(null);setPackageData(null);setDelivery(null);resetConfirmation()};
 const invalidateAfterVariant=()=>{setPackageData(null);setDelivery(null);resetConfirmation()};
 const reloadReadiness=async()=>{const current=await mediaApi.publicationReadiness(id,{distributionMode:'ORGANIC',format:'STATIC_CARD',channel:'INSTAGRAM'});setReadiness(current);return current};
 const generate=()=>run('static',async()=>{invalidateAfterStatic();setStaticResult(await mediaApi.staticPreview(id,'STATIC_CARD'));await reloadReadiness();setMessage('Imagem gerada. Prepare novamente a variante, o pacote e a entrega.')});
 const renderVariant=()=>run('variant',async()=>{invalidateAfterVariant();const result=await mediaApi.renderChannelVariant(id,{channel:'INSTAGRAM',distributionMode:'ORGANIC',placement:'INSTAGRAM_FEED',creativeFormat:'STATIC_CARD'});setVariant(result);await reloadReadiness();setMessage('Imagem preparada para o Instagram. Prepare novamente o pacote e a entrega.')});
 const preparePackage=()=>run('package',async()=>{const result=await mediaApi.preparePublicationPackage(id,{distributionMode:'ORGANIC',format:'STATIC_CARD',channel:'INSTAGRAM',audioPlan:{mode:'NONE'},disclosurePlan:{affiliateRelationship:'AFFILIATE_LINK',requirementStatus:'REQUIRED',status:'PRESENT',text:disclosure,placement:'CAPTION',platformToolRequired:false},trackingPlan:{}});setPackageData(result);setReadiness(result);setDelivery(null);setMessage('Pacote de publicação preparado.')});
 const prepareDelivery=()=>run('delivery',async()=>{if(!packageData)throw new Error('Prepare primeiro o pacote de publicação.');const result=await mediaApi.prepareMediaDelivery({publicationCandidateId:packageData.publicationCandidateId,channel:'INSTAGRAM',format:'STATIC_CARD',assetFiles:packageData.assetFiles});setDelivery(result);setMessage(result.readiness==='READY'?'Entrega de mídia pronta.':'A entrega de mídia ainda possui pendências.')});
 const refreshHistorySafely=async()=>{try{const rows=await mediaApi.publicationExecutions(id);setHistory(rows);return rows}catch{return null}};
 const publish=()=>run('publish',async()=>{if(!packageData||!confirmed||!deliveryUsable(delivery))return;try{const result=await mediaApi.instagramPublish(id,packageData.publicationCandidateId);setConfirmOpen(false);setConfirmed(false);setMessage(result.status==='PUBLISHED'?'Publicado com sucesso.':'Solicitação registrada.')}catch(e){const rows=await refreshHistorySafely();if(e instanceof PublicationApiError&&e.code==='EXECUTION_ALREADY_ATTEMPTED'){setConfirmOpen(false);setConfirmed(false);setRetryTarget(rows?.find(x=>x.status==='FAILED'&&x.remoteRequestExecuted&&x.publicationCandidateId===packageData.publicationCandidateId)??null);setError('Esta publicação já teve uma tentativa que falhou. A tentativa anterior não será repetida automaticamente.');return}throw e}finally{await refreshHistorySafely()}});
 const retry=()=>run('retry',async()=>{if(!retryTarget||!retryConfirmed||!canPublish)return;const failedExecutionId=retryTarget.executionId;try{const result=await mediaApi.retryInstagramPublication(failedExecutionId);setRetryOpen(false);setRetryConfirmed(false);setRetryTarget(null);setError('');setMessage(result.status==='PUBLISHED'?'Nova tentativa publicada com sucesso.':'Nova tentativa registrada.')}finally{await refreshHistorySafely()}});
 const preview=useMemo(()=>delivery?.hostedAssets?.[0]?.publicUrl||(variant?.files?.[0]?mediaApi.channelVariantContentUrl(id,variant.profile.profileId!,variant.files[0]):staticResult?.files?.[0]?mediaApi.staticContentUrl(id,'STATIC_CARD',staticResult.files[0].split('/').pop()!):null),[delivery,variant,staticResult,id]);
 if(!base&&!error)return <Loading/>;if(!base)return <ErrorState error={new Error(error)} retry={load}/>;const{creative,campaign,connection,settings}=base;const approved=creative.status==='APPROVED',connected=connection.status==='CONNECTED'&&connection.publicationConnectorReadiness==='READY',variantReady=variant?.adaptationStatus==='UP_TO_DATE',packageReady=!!packageData&&!!readiness&&['READY','READY_WITH_WARNINGS'].includes(packageData.readinessStatus)&&packageData.blockers.length===0&&packageData.publicationCandidateId===readiness.publicationCandidateId&&packageData.channelVariantFingerprint===readiness.channelVariantFingerprint&&sameFiles(packageData.assetFiles,readiness.assetFiles),deliveryReady=deliveryUsable(delivery)&&!!packageData&&delivery?.publicationCandidateId===packageData.publicationCandidateId,deliveryExpired=!!delivery&&delivery.readiness==='READY'&&!deliveryUsable(delivery),switchesReady=settings.systemAutomationEnabled&&settings.publishingEnabled,canPublish=approved&&connected&&variantReady&&packageReady&&deliveryReady&&switchesReady;
 return <div className="instagram-publish"><header className="page-head"><div><span>PUBLICAÇÃO INSTAGRAM</span><h1>{creative.name}</h1><p>Publicação orgânica de uma imagem, sempre com confirmação explícita.</p></div><Link className="ghost-button" to={`/criativos/${id}`}>Voltar ao Creative</Link></header>{error&&<p role="alert" className="inline-error">{error}</p>}{message&&<p role="status" className="media-notice">{message}</p>}
 <div className="publish-steps">
 <Section title="1. Conexão"><div className="publish-row"><div><b>{connected?'Instagram conectado':connection.status==='AUTHENTICATION_REQUIRED'?'A conexão com o Instagram precisa ser renovada.':'Instagram não conectado'}</b><small>{connection.username?'@'+connection.username:'Conecte uma conta profissional'} · {connection.accountType?label(connection.accountType):'Conta não identificada'}</small></div><Badge tone={connected?'success':'warning'}>{connected?'Pronta':'Pendente'}</Badge></div>{!connected&&<button type="button" className="primary-button" disabled={busy==='connect'} onClick={()=>run('connect',async()=>{const auth=await mediaApi.instagramAuthorize();window.open(auth.authorizationUrl,'instagram-oauth','popup,width=620,height=760')})}>{connection.status==='AUTHENTICATION_REQUIRED'?'Reconectar Instagram':'Conectar Instagram'}</button>}<p className="muted">Credenciais e tokens nunca são exibidos.</p></Section>
  <Section title="2. Conteúdo"><div className="publish-summary"><div><small>Creative</small><b>{creative.title||creative.name}</b></div><div><small>Campanha</small><b>{campaign.name}</b></div><div><small>Status</small><Badge tone={statusTone(creative.status)}>{creativeStatusLabel(creative.status)}</Badge></div><div><small>CTA</small><b>{creative.cta||'Não definido'}</b></div></div>{!approved&&<p className="blocking-note">Somente um Creative aprovado pode ser publicado.</p>}<button type="button" className="primary-button" disabled={!approved||!!busy} onClick={generate}>{busy==='static'?'Gerando…':readiness?.assetFiles.length?'Gerar imagem novamente':'Gerar imagem'}</button></Section>
  <Section title="3. Preparação para Instagram"><p>Formato: Card estático · Placement: Feed do Instagram</p><button type="button" className="primary-button" disabled={!approved||!readiness?.assetFiles.length||!!busy} onClick={renderVariant}>{busy==='variant'?'Preparando…':variantReady?'Preparar novamente':'Preparar para Instagram'}</button>{variant&&<><div className="publish-summary"><div><small>Dimensões</small><b>{variant.width} × {variant.height}</b></div><div><small>Proporção</small><b>{variant.aspectRatio}</b></div><div><small>Status</small><b>{variantReady?'Pronta':'Pendente'}</b></div></div>{variant.warnings?.length>0&&<ul className="warning-list">{variant.warnings.map(x=><li key={x}>{label(x)}</li>)}</ul>}</>}{preview&&<img className="publish-preview" src={preview} alt="Preview final para o Instagram"/>}</Section>
  <Section title="4. Readiness"><div className="publish-row"><b>{statusLabel[readiness?.readinessStatus??'']??'Não avaliada'}</b><Badge tone={readiness?.readinessStatus==='READY'?'success':readiness?.readinessStatus==='READY_WITH_WARNINGS'?'warning':'danger'}>{readiness?.readinessStatus==='BLOCKED'?'Pendente':'Verificada'}</Badge></div>{readiness?.blockers.length?<ul>{readiness.blockers.map(x=><li key={x.code}>{blockerLabel[x.code]??x.message}</li>)}</ul>:<p>Nenhuma pendência técnica no readiness atual.</p>}</Section>
  <Section title="5. Disclosure e pacote"><label className="publish-field">Texto do disclosure<textarea value={disclosure} onChange={e=>{setDisclosure(e.target.value);setPackageData(null);setDelivery(null);resetConfirmation()}}/></label><p className="muted">Link de afiliado · Obrigatório · Presente · Legenda</p><button type="button" className="primary-button" disabled={!approved||!variantReady||!disclosure.trim()||!!busy} onClick={preparePackage}>{busy==='package'?'Preparando…':'Preparar publicação'}</button>{packageData&&<div className="publish-summary"><div><small>Pacote</small><b>{statusLabel[packageData.readinessStatus]??packageData.readinessStatus}</b></div><div><small>Arquivos</small><b>{packageData.assetFiles.length}</b></div><div><small>Destino</small><b>{packageData.destinationUrl?'Configurado':'Pendente'}</b></div></div>}</Section>
  <Section title="6. Media Delivery"><button type="button" className="primary-button" disabled={!packageReady||!!busy} onClick={prepareDelivery}>{busy==='delivery'?'Preparando…':'Preparar entrega de mídia'}</button>{delivery&&<><div className="publish-summary"><div><small>Status</small><b>{deliveryReady?'Pronta':'Não pronta'}</b></div><div><small>Provider</small><b>{delivery.provider.provider}</b></div><div><small>Validade</small><b>{delivery.hostedAssets?.[0]?.expiresAt?new Date(delivery.hostedAssets[0].expiresAt).toLocaleString('pt-BR'):'Pendente'}</b></div></div>{deliveryExpired&&<p className="blocking-note">A entrega de mídia expirou. Prepare novamente a entrega antes de publicar.</p>}</>}</Section>
  <Section title="7. Confirmação e resultado">{!settings.publishingEnabled&&<p className="blocking-note">Publicação desabilitada nas configurações. <Link to="/configuracoes">Ir para Configurações</Link></p>}{!settings.systemAutomationEnabled&&<p className="blocking-note">O Kill Switch está ativo.</p>}<button type="button" className="danger-button" disabled={!canPublish||!!busy} onClick={()=>setConfirmOpen(true)}>Revisar e publicar</button>{retryTarget&&<div className="blocking-note"><b>Esta publicação já teve uma tentativa que falhou.</b><p>A tentativa anterior não será repetida automaticamente.</p><button type="button" className="danger-button" disabled={!canPublish||!!busy} onClick={()=>setRetryOpen(true)}>NOVA TENTATIVA</button></div>}</Section>
  <Section title="Histórico de publicação">{history.length?<div className="execution-list">{history.map(x=><article key={x.executionId}><Badge tone={executionTone(x.status)}>{statusLabel[x.status]??x.status}</Badge><b>Tentativa {x.attemptNumber}</b><span>{x.publishedAt?new Date(x.publishedAt).toLocaleString('pt-BR'):new Date(x.createdAt).toLocaleString('pt-BR')}</span>{x.platformMediaId&&<small>Publicação registrada na plataforma</small>}{x.status==='FAILED'&&<small>A tentativa foi registrada e não será repetida automaticamente.</small>}</article>)}</div>:<p className="muted">Nenhuma tentativa registrada.</p>}</Section>
 </div>{confirmOpen&&<div className="publish-modal-backdrop" role="presentation"><div className="publish-modal" role="dialog" aria-modal="true" aria-labelledby="publish-title"><h2 id="publish-title">Confirmar publicação real</h2><p>Conta: <b>{connection.username?'@'+connection.username:connection.accountDisplayName}</b></p><p>Creative: <b>{creative.title||creative.name}</b></p>{preview&&<img className="publish-preview" src={preview} alt="Imagem que será publicada"/>}<p><b>Legenda e disclosure</b></p><p>{creative.cta}</p><p>{disclosure}</p><label className="confirm-check"><input type="checkbox" checked={confirmed} onChange={e=>setConfirmed(e.target.checked)}/> Confirmo que revisei imagem e legenda</label><div className="button-row"><button type="button" className="ghost-button" disabled={busy==='publish'} onClick={resetConfirmation}>Cancelar</button><button type="button" className="danger-button" disabled={!confirmed||!canPublish||busy==='publish'} onClick={publish}>{busy==='publish'?'Publicando…':'PUBLICAR NO INSTAGRAM'}</button></div></div></div>}{retryOpen&&retryTarget&&<div className="publish-modal-backdrop" role="presentation"><div className="publish-modal" role="dialog" aria-modal="true" aria-labelledby="retry-title"><h2 id="retry-title">Confirmar nova tentativa</h2><p>Será criada a tentativa {retryTarget.attemptNumber+1}. A tentativa anterior permanecerá no histórico.</p><p>Conta: <b>{connection.username?'@'+connection.username:connection.accountDisplayName}</b></p><p>Creative: <b>{creative.title||creative.name}</b></p>{preview&&<img className="publish-preview" src={preview} alt="Imagem da nova tentativa"/>}<p>{creative.cta}</p><p>{disclosure}</p><label className="confirm-check"><input type="checkbox" checked={retryConfirmed} onChange={e=>setRetryConfirmed(e.target.checked)}/> Confirmo que revisei a entrega atual, a imagem e a legenda</label><div className="button-row"><button type="button" className="ghost-button" disabled={busy==='retry'} onClick={()=>{setRetryOpen(false);setRetryConfirmed(false)}}>Cancelar</button><button type="button" className="danger-button" disabled={!retryConfirmed||!canPublish||busy==='retry'} onClick={retry}>{busy==='retry'?'Tentando novamente…':'CONFIRMAR NOVA TENTATIVA'}</button></div></div></div>}</div>;
}
