import { useCallback, useState } from 'react';
import { api } from '../api/client';
import { Badge, Empty, ErrorState, Loading, Section } from '../components/ui';
import { useLoad } from '../hooks';
import { date, label, parseUtcTimestamp, statusTone } from '../lib/presentation';
import type { CatalogDiscoveryResult, RadarRun, RadarSignal, TriageResult, EnrichmentResult, PreferredRadarResult } from '../types';

const SOURCE_LABELS = ['TRENDS_GLOBAL', 'TRENDS_CATEGORY', 'HIGHLIGHTS_CATEGORY'];

export function RadarPage() {
  const loader = useCallback(async () => {
    const [status, categories, runs, settings] = await Promise.all([api.radarStatus(), api.radarCategories(), api.radarRuns(), api.settings()]);
    const signals = runs[0] ? await api.radarSignals(runs[0].id) : [];
    return { status, categories, runs, settings, selectedRun: runs[0] ?? null, signals };
  }, []);
  const { data, error, loading, refresh } = useLoad(loader);
  const [category, setCategory] = useState('');
  const [directedQuery, setDirectedQuery] = useState('');
  const [directedCategory, setDirectedCategory] = useState('');
  const [directed, setDirected] = useState<Awaited<ReturnType<typeof api.directedOpportunitySearch>>|null>(null);
  const [busy, setBusy] = useState<'sync'|'run'|'history'|'discover'|'triage'|'enrich'|'directed'|'preferred'|null>(null);
  const [preferredResult,setPreferredResult]=useState<PreferredRadarResult|null>(null);
  const [actionError, setActionError] = useState<string|null>(null);
  const [selectedRun, setSelectedRun] = useState<RadarRun|null>(null);
  const [signals, setSignals] = useState<RadarSignal[]|null>(null);
  const [discovery, setDiscovery] = useState<CatalogDiscoveryResult|null>(null);
  const [triage, setTriage] = useState<TriageResult|null>(null);
  const [enrichment, setEnrichment] = useState<EnrichmentResult|null>(null);
  async function sync() { setBusy('sync'); setActionError(null); try { await api.syncRadarCategories(); await refresh(); } catch (reason) { setActionError(reason instanceof Error ? reason.message : 'Não foi possível sincronizar.'); } finally { setBusy(null); } }
  async function run() { setBusy('run'); setActionError(null); try { const created = await api.createRadarRun(category || null); const found = await api.radarSignals(created.id); setSelectedRun(created); setSignals(found); await refresh(); } catch (reason) { setActionError(reason instanceof Error ? reason.message : 'Não foi possível executar o Radar.'); } finally { setBusy(null); } }
  async function openRun(item: RadarRun) { setBusy('history'); setActionError(null); try { setSelectedRun(item); setSignals(await api.radarSignals(item.id)); } catch (reason) { setActionError(reason instanceof Error ? reason.message : 'Não foi possível abrir a execução.'); } finally { setBusy(null); } }
  async function discover() { if (!currentRun) return; setBusy('discover'); setActionError(null); try { setDiscovery(await api.resolveRadarProducts(currentRun.id)); } catch (reason) { setActionError(reason instanceof Error ? reason.message : 'Não foi possível descobrir produtos.'); } finally { setBusy(null); } }
  async function triageCandidates() { if (!currentRun) return; setBusy('triage'); setActionError(null); try { setTriage(await api.triageRadarCandidates(currentRun.id)); } catch (reason) { setActionError(reason instanceof Error ? reason.message : 'Não foi possível triar candidatos.'); } finally { setBusy(null); } }
  async function enrichCandidates() { if (!currentRun) return; setBusy('enrich'); setActionError(null); try { setEnrichment(await api.enrichRadarCandidates(currentRun.id)); } catch (reason) { setActionError(reason instanceof Error ? reason.message : 'Não foi possível enriquecer evidências.'); } finally { setBusy(null); } }
  async function directedSearch() { setBusy('directed'); setActionError(null); setDirected(null); try { setDirected(await api.directedOpportunitySearch(directedQuery, directedCategory || null)); await refresh(); } catch (reason) { const code=reason instanceof Error ? reason.message : ''; setActionError(code==='NO_MATCH_IN_CATEGORY' ? 'A busca parece pertencer a outra categoria. Use Categoria Automática ou altere a categoria.' : code==='BLOCKED_POLICY' ? 'Esta busca não é elegível para descoberta comercial.' : 'Não foi possível buscar oportunidades.'); } finally { setBusy(null); } }
  async function runPreferred(){setBusy('preferred');setActionError(null);try{setPreferredResult(await api.runPreferredRadar());await refresh()}catch{setActionError('Não foi possível executar as categorias preferidas.')}finally{setBusy(null)}}
  if (loading) return <Loading />;
  if (error || !data) return <ErrorState error={error ?? new Error('Sem dados')} retry={refresh} />;
  const currentRun = selectedRun ?? data.selectedRun;
  const currentSignals = signals ?? data.signals;
  const categoryNames = Object.fromEntries(data.categories.map(item => [item.externalCategoryId, item.name]));
  const preferred=new Set(data.settings.preferredMarketplaceCategoryIds ?? []); const preferredCategories=data.categories.filter(x=>preferred.has(x.externalCategoryId)); const otherCategories=data.categories.filter(x=>!preferred.has(x.externalCategoryId));
  return <><header className="page-head"><div><span>SINAIS OFICIAIS</span><h1>Radar</h1><p>Observe tendências e destaques do Mercado Livre sem scoring ou enriquecimento artificial.</p></div></header>
    <Section title="Status do Radar"><div className="connection-grid"><div><small>Provider</small><b>Mercado Livre</b></div><div><small>Site</small><b>{data.status.siteId}</b></div><div><small>Status</small><Badge tone={statusTone(data.status.status)}>{label(data.status.status)}</Badge></div></div><div className="source-status">{SOURCE_LABELS.map(key => <span key={key}>{label(key)} <Badge tone={statusTone(data.status.capabilities[key] ?? 'UNKNOWN')}>{label(data.status.capabilities[key] ?? 'UNKNOWN')}</Badge></span>)}</div><p className="timestamp">Limitações conhecidas: busca geral {label(data.status.capabilities.MARKETPLACE_SEARCH ?? 'UNKNOWN')} · detalhes de item {label(data.status.capabilities.ITEM_DETAILS ?? 'UNKNOWN')}. Essas capacidades são opcionais para o Radar.</p></Section>
    <Section title="Executar Radar"><div className="diagnostic-controls"><label>Categoria<select aria-label="Categoria do Radar" value={category} onChange={event => setCategory(event.target.value)}><option value="">Somente tendências gerais</option>{data.categories.map(item => <option key={item.id} value={item.externalCategoryId}>{item.name} ({item.externalCategoryId})</option>)}</select></label><button className="primary-button" disabled={busy !== null} onClick={run}>{busy === 'run' ? 'Executando…' : 'Executar Radar'}</button><button className="ghost-button" disabled={busy !== null} onClick={sync}>{busy === 'sync' ? 'Sincronizando…' : 'Sincronizar categorias'}</button></div>{data.categories.length === 0 && <p className="timestamp">Sincronize as categorias para executar fontes por categoria.</p>}{actionError && <p className="inline-error" role="alert">{actionError}</p>}</Section>
    <Section title="Categorias preferidas">{preferredCategories.length?<><p>{preferredCategories.map(x=>x.name).join(' · ')}</p><p className="timestamp">Tendências globais: {data.settings.includeGlobalTrendsOutsidePreferredCategories?'Incluídas':'Não incluídas'}</p><button className="primary-button" disabled={busy!==null} onClick={runPreferred}>{busy==='preferred'?'Executando…':'Executar categorias preferidas'}</button></>:<p>Nenhuma categoria preferida configurada. <a href="/configuracoes">Configurar categorias</a></p>}{preferredResult&&<><p className="timestamp">{label(preferredResult.status)} · {preferredResult.categoriesCompleted} concluídas · {preferredResult.categoriesPartial} parciais · {preferredResult.categoriesFailed} com falha · {preferredResult.signalsFound} sinais encontrados · {preferredResult.runsCreated} runs criadas.</p>{preferredResult.categoriesFailed>0&&preferredResult.globalIncluded&&!preferredResult.globalSucceeded&&<p className="inline-error">Algumas categorias e as tendências globais não puderam ser processadas.</p>}{preferredResult.categoriesFailed>0&&!(preferredResult.globalIncluded&&!preferredResult.globalSucceeded)&&<p className="inline-error">Algumas categorias não puderam ser processadas.</p>}{preferredResult.categoriesFailed===0&&preferredResult.globalIncluded&&!preferredResult.globalSucceeded&&<p className="inline-error">As tendências globais não puderam ser processadas.</p>}{preferredResult.categoriesPartial>0&&<p className="timestamp">Algumas categorias foram processadas parcialmente.</p>}<div className="compact-list">{preferredResult.runs.map(x=><div key={x.runId}><span><b>{x.categoryId?categoryNames[x.categoryId]??x.categoryId:'Tendências globais'}</b><small>{x.discoveredCount} sinais</small></span><Badge tone={statusTone(x.status)}>{label(x.status)}</Badge></div>)}</div></>}</Section>
    <Section title="Buscar oportunidade"><div className="diagnostic-controls"><label>O que você quer analisar?<input aria-label="O que você quer analisar?" value={directedQuery} onChange={event=>setDirectedQuery(event.target.value)} placeholder="parafusadeira 20v" /></label><label>Categoria<select aria-label="Categoria da busca" value={directedCategory} onChange={event=>setDirectedCategory(event.target.value)}><option value="">Automática</option>{preferredCategories.length>0&&<optgroup label="Preferidas">{preferredCategories.map(item=><option key={item.id} value={item.externalCategoryId}>{item.name}</option>)}</optgroup>}<optgroup label={preferredCategories.length?'Outras categorias':'Categorias'}>{otherCategories.map(item=><option key={item.id} value={item.externalCategoryId}>{item.name}</option>)}</optgroup></select></label><button className="primary-button" disabled={busy!==null || directedQuery.trim().length<2} onClick={directedSearch}>{busy==='directed'?'Buscando…':'Buscar oportunidades'}</button></div>{directed && <><p className="timestamp">Busca: {directed.query} · Domínio identificado: {directed.categoryContext.domainName ?? 'Não disponível'} · Categoria identificada: {directed.categoryContext.predictedCategoryName ?? 'Não disponível'}.</p>{directed.policyStatus==='BLOCKED_POLICY' ? <p className="inline-error">Esta busca não é elegível para descoberta comercial.</p> : directed.reasonCode==='NO_MATCH_IN_CATEGORY' ? <p className="inline-error">A busca parece pertencer a outra categoria. Use Categoria Automática ou altere a categoria.</p> : <><p className="timestamp">{directed.productsFoundRaw} produtos encontrados · {directed.productsSelected} produtos selecionados · {directed.topCandidates.length} candidatos priorizados.</p><div className="compact-list">{directed.topCandidates.map(item=><a key={item.candidateId} href={`/curator/${item.candidateId}`}><span><b>{item.title}</b><small>{item.catalogProductId} · Relevância {item.relevanceScore ?? '—'} · Triagem {item.triageScore}</small></span><Badge tone={statusTone(item.triageStatus)}>{label(item.triageStatus)}</Badge><strong>Abrir na Curadoria</strong></a>)}</div></>}</>}</Section>
    <Section title="Resultado selecionado">{currentRun ? <><RunSummary run={currentRun} categoryName={currentRun.requestedCategoryId ? categoryNames[currentRun.requestedCategoryId] : null} /><div className="diagnostic-controls"><button className="primary-button" type="button" disabled={busy !== null || !['COMPLETED','PARTIAL'].includes(currentRun.status)} onClick={discover}>{busy === 'discover' ? 'Descobrindo…' : 'Descobrir produtos'}</button><button className="ghost-button" type="button" disabled={busy !== null || !['COMPLETED','PARTIAL'].includes(currentRun.status)} onClick={triageCandidates}>{busy === 'triage' ? 'Triando…' : 'Triar candidatos'}</button><button className="ghost-button" type="button" disabled={busy !== null || !['COMPLETED','PARTIAL'].includes(currentRun.status)} onClick={enrichCandidates}>{busy === 'enrich' ? 'Enriquecendo…' : 'Enriquecer evidências'}</button></div>{discovery && <p className="timestamp">{discovery.signalsProcessed} de {discovery.signalsEligible} sinais elegíveis processados{discovery.signalsSkippedByLimit ? ` · ${discovery.signalsSkippedByLimit} não processados pelo limite` : ''} · {discovery.productsSelected} produtos selecionados de {discovery.productsFoundRaw} encontrados · {discovery.candidatesCreated} novos · {discovery.candidatesReused} existentes{discovery.policyBlockedCount ? ` · ${discovery.policyBlockedCount} bloqueados por política` : ''}. {discovery.candidateIds.length ? <a href={`/curator/${discovery.candidateIds[0]}`}>Abrir candidatos</a> : null}</p>}{triage && <p className="timestamp">Top candidatos desta execução: {triage.candidatesEvaluated} avaliados · {triage.topCandidates.length} marcados para enriquecimento. {triage.topCandidates[0] ? <a href={`/curator/${triage.topCandidates[0].candidateId}`}>Abrir melhor candidato</a> : null}</p>}{enrichment && <><p className="timestamp">{enrichment.candidatesProcessed} candidatos processados · {enrichment.catalogAvailableCount} catálogos disponíveis · {enrichment.commercialEvidenceAvailableCount} com evidências comerciais · {enrichment.candidatesWithoutBuyBox} sem buy box · {enrichment.priceAvailableCount} com preço · {enrichment.reviewsAvailableCount} com avaliações · {enrichment.sellerReputationAvailableCount} com reputação do vendedor.</p>{enrichment.commercialEvidenceAvailableCount === 0 && <p className="timestamp">Nenhuma evidência comercial disponível nesta execução.</p>}<p className="timestamp">{enrichment.evidenceAdded} evidências novas · {enrichment.evidenceChanged} alteradas · {enrichment.evidenceUnchanged} sem mudança.</p></>}</> : <Empty>Nenhuma execução do Radar registrada.</Empty>}</Section>
    <Section title="Sinais encontrados">{busy === 'history' ? <Loading /> : currentSignals.length ? <div className="table-wrap"><table><thead><tr><th>Fonte</th><th>Posição</th><th>Sinal / termo</th><th>Tipo</th><th>ID externo</th><th>Categoria</th><th>Observado em</th><th>Ação</th></tr></thead><tbody>{currentSignals.map(item => <tr key={item.id}><td>{label(item.sourceType)}</td><td>{item.rank ? `#${item.rank}` : '—'}</td><td>{item.displayText ?? '—'}</td><td>{label(item.entityType)}</td><td>{item.externalId ?? '—'}</td><td>{item.categoryExternalId ? categoryNames[item.categoryExternalId] ?? item.categoryExternalId : '—'}</td><td>{date(item.observedAt)}</td><td><button onClick={async()=>{const c=await api.investigate(item.id);window.location.assign('/curator/'+c.id)}}>Investigar</button></td></tr>)}</tbody></table></div> : <Empty>Nenhum sinal encontrado nesta execução.</Empty>}</Section>
    <Section title="Histórico de execuções">{data.runs.length ? <div className="compact-list run-history">{data.runs.map(item => <button key={item.id} onClick={() => openRun(item)}><span><b>{date(item.startedAt)}</b><small>{item.requestedCategoryId ? categoryNames[item.requestedCategoryId] ?? item.requestedCategoryId : 'Tendências gerais'}</small></span><Badge tone={statusTone(item.status)}>{label(item.status)}</Badge><strong>{item.discoveredCount} sinais</strong></button>)}</div> : <Empty>O histórico está vazio.</Empty>}</Section></>;
}

function RunSummary({ run, categoryName }: { run: RadarRun; categoryName: string|null|undefined }) {
  const duration = run.finishedAt ? Math.max(0, parseUtcTimestamp(run.finishedAt).getTime() - parseUtcTimestamp(run.startedAt).getTime()) : null;
  return <div className="run-summary"><div><small>Status</small><Badge tone={statusTone(run.status)}>{label(run.status)}</Badge></div><div><small>Horário</small><b>{date(run.startedAt)}</b></div><div><small>Fontes concluídas</small><b>{run.sourcesSucceeded.map(label).join(', ') || 'Nenhuma'}</b></div><div><small>Sinais</small><b>{run.discoveredCount}</b></div><div><small>Categoria</small><b>{categoryName ?? run.requestedCategoryId ?? 'Não informada'}</b></div><div><small>Duração</small><b>{duration === null ? 'Em execução' : `${duration} ms`}</b></div></div>;
}
